### ISSUE TITLE
Definition for Sequelize

### ISSUE THREAD

**Issue by Janekk** [borisyankov/DefinitelyTyped#1773]
Could you please add a reference to Sequelize (http://sequelizejs.com/) - an ORM for node?

**Comment by EToreo** [comment]
+1

**Comment by PLEEROCK** [comment]
+1

**Comment by rattrayalex** [comment]
This issue can now be closed, correct? https://github.com/borisyankov/DefinitelyTyped/blob/master/sequelize/sequelize-tests.ts

**Comment by vvakame** [comment]
yep, thanks!

**Comment by manuelfink** [comment]
I'm new to typescript. How can this typings be used?
