### ISSUE TITLE
Request: ES6 extensions (es6-shim)

### ISSUE THREAD

**Issue by Bartvds** [borisyankov/DefinitelyTyped#1804]
For new browsers but also https://github.com/paulmillr/es6-shim

@vvakame Weren't you working on these some time ago? Did it work out?

Not sure how to do it as they extend the native types.

**Comment by laktak** [comment]
+1

**Comment by rcchen** [comment]
Looks like this was addressed in https://github.com/borisyankov/DefinitelyTyped/pull/4326, this issue should be closed.

**Comment by vvakame** [comment]
thanks!
