### ISSUE TITLE
Definition Request: socket.io v1.0

### ISSUE THREAD

**Issue by pspi** [borisyankov/DefinitelyTyped#2687]
First examples from http://socket.io/docs/server-api/ dont work with current (pre 1.0?) definitions.

```
var io = require('socket.io')();
// or
var Server = require('socket.io');
var io = new Server();
```

**Comment by elisee** [comment]
This issue can be closed, the current socket.io.d.ts supports 1.2+

**Comment by vvakame** [comment]
@elisee thank you for your notice!
