### ISSUE TITLE
ChartJS Definition

### ISSUE THREAD

**Issue by basarat** [borisyankov/DefinitelyTyped#2830]
Definition Request for Chartjs : http://www.chartjs.org/

As a side note I deleted the current folder as it is only `///reference`ing DXChart and should not camp in the `chartjs` folder. User report : http://stackoverflow.com/questions/25856878/code-for-chartjs-typescript-definition-file

**Comment by cabralRodrigo** [comment]
This definitions have already been created  ([ChartJS](https://github.com/borisyankov/DefinitelyTyped/tree/master/chartjs)). So... this issue has to be closed?
