### ISSUE TITLE
Add support for chai-as-promised

### ISSUE THREAD

**Issue by ThomasDalla** [borisyankov/DefinitelyTyped#3030]
**chai-as-promised** adds a couple features for chai to support promises.
It also adds a couple assertions such as "is.fulfilled" which are not currently recognised by the normal chai.

chai-as-promised: https://github.com/domenic/chai-as-promised/

**Comment by jmlane** [comment]
FYI https://github.com/borisyankov/DefinitelyTyped/tree/master/chai-as-promised exists now.
