### ISSUE TITLE
accept declaration is missing from supertest.Test and superagent.Request declarations

### ISSUE THREAD

**Issue by LivesleyWA** [borisyankov/DefinitelyTyped#3356]
It's in super agent.

**Comment by horiuchi** [comment]
What, specifically, is declaration missing?

**Comment by LivesleyWA** [comment]
As I mentioned

accept - it’s in the javascript

so I can do


SUPERTEST_MODULE(server)
    .get("/scripts/lmU9GwyDakKIycXPujgJZw?order=name")
    .type("application/vnd.ilexium-com.aaascript+json; version=20141015")
    .accept("application/vnd.ilexium-com.aaascript+json; version=20141015")

I attach my adjusted code.

**Comment by horiuchi** [comment]
I was updated the definition.
