### ISSUE TITLE
Errors in definitions in VS2013 

### ISSUE THREAD

**Issue by mondss** [borisyankov/DefinitelyTyped#3532]
Hi,

I'm not sure if I'm being completely stupid or if I've done something wrong.

Whenever I add the angular js definitely typed definitions to my project via nuget, I get over 100 errors in the error prompt.

These generally consist of 'Identifier expected', 'Default arguments are only allowed in implementation',  'Build: = expected' etc. Do I have to update my TSLint (which is what I presume is causing the problems) or is there anything else I can do?

Thanks

**Comment by xt0rted** [comment]
TSLint hasn't been updated to support TypeScript 1.4 yet so union types and any other new language features will most likely cause errors. I had the same problem and had to turn off TSLint for now until a new release comes out.

**Comment by bigerock** [comment]
how do you turn off TSLint? i thought it was part of web essentials. no?

**Comment by xt0rted** [comment]
@bigerock  [TSLint](https://github.com/palantir/tslint) is a nodejs based utility but is included in Web Essentials.

The settings to turn this on or off are under Tools > Options > Web Essentials > TypeScript > Linter

**Comment by bigerock** [comment]
thanks! i turned off 'run on save' so now it's not running on save or build. 

i still get the errors mentioned though. any thoughts?

**Comment by bigerock** [comment]
i see - i updated to the latest angularjs definitelytyped and this is what broke it. i downgraded to a few versions previous and now it's not throwing those errors. hope this helps someone else.

**Comment by vko-online** [comment]
Any fix?

**Comment by mondss** [comment]
Hi All,

I fixed my issue by installing this latest TypeScript update: https://visualstudiogallery.msdn.microsoft.com/2d42d8dc-e085-45eb-a30b-3f7d50d55304.

Fixed it for me and I no longer get any errors, so I'm going to close this off.
