### ISSUE TITLE
Update pixi definition file

### ISSUE THREAD

**Issue by nikeee** [borisyankov/DefinitelyTyped#3541]
pixi is now at 2.2.3 and the current definition file is for version 1.3.0.
There seem to be some changes. For example, the `Sprite` object now has a `tint` property.

I currently don't have the time to update the definition, but maybe somebody else does (@xperiments?).

**Comment by nikeee** [comment]
I'm now working on it:
https://github.com/nikeee/DefinitelyTyped/tree/pixi-update

**Comment by doskallemaskin** [comment]
Make sure you're not doing extra work, is this still active? 
https://github.com/pixijs/pixi-typescript/ is pretty up to date with newest pixi and being maintained.

**Comment by xperiments** [comment]
I am on holidays, I will try to find some time to make the changes when I
come back second week of august.
