### ISSUE TITLE
AzureMobileServicesClient.d.ts missing invokeApi method

### ISSUE THREAD

**Issue by JCKodel** [borisyankov/DefinitelyTyped#3587]
WindowsAzure.MobileServiceClient prototype should have an invokeApi method, as described in documentation:

https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.mobileservices.mobileserviceclient.aspx

That method would call a WebApi custom method that is not a Table controller

**Comment by vvakame** [comment]
@JCKodel please send a PR!
