### ISSUE TITLE
AngularJS externs, ng.IAngularStatic vs angular

### ISSUE THREAD

**Issue by mprobst** [borisyankov/DefinitelyTyped#3670]
The externs for AngularJS define:
```js
declare var angular: ng.IAngularStatic;
// Support AMD require
declare module 'angular' {  // NB: doesn't currently work with TypeScript 1.4 AFAICT
    export = angular;
}
declare module ng {
  // ... definitions, including IAngularStatic
}
```

Is there a way to use `.d.ts` files like this without triple slash references (`/// <reference path=...>`)? If this would define:
```js
export = ng;

declare module ng {
  function module(...): ng.Module;
}
```

... then user code could simple and consistently write:
```js
import angular = require('angular');
var myMod: angular.Module = angular.module(...);
```

Is there a particular reason to split into an `angular` variable of type `ng.IAngularStatic` and the `ng` module?

**Comment by awerlang** [comment]
> Is there a particular reason to split into an angular variable of type ng.IAngularStatic and the ng module?

A variable is a runtime thing, so it must be the same as angularJS wants it to be. `ng` is a compile-time thing, I guess it is so in order to be in sync with angular docs (https://docs.angularjs.org/api/ng/). For instance, you can't require an `angular` module on `angular.module()`.
