### ISSUE TITLE
[should.js] which.is support in Wesbstorm

### ISSUE THREAD

**Issue by hellboy81** [borisyankov/DefinitelyTyped#3727]
In the  following line
```js
myObj.should.have.property('myProperty').which.is.a.String
````
there are some issues:
- `which` is not recognized by Intellisense
- Statement line is yellow highlighted :
![2015-02-24 01 webstorm screenshot](https://cloud.githubusercontent.com/assets/341600/6348443/f28ada9a-bc1f-11e4-9392-b4bb47c13056.png)

**Comment by vvakame** [comment]
@hellboy81 please report to jetbrains.
https://youtrack.jetbrains.com/dashboard
