### ISSUE TITLE
Modernizr Prefixed definition returns boolean

### ISSUE THREAD

**Issue by iambacon** [borisyankov/DefinitelyTyped#3728]
When trying to use `Modernizr.prefixed()` the type definition returns `boolean`

```
prefixed(): boolean;
prefixed(property: string): boolean;
prefixed(property: string, obj: any, element?: any): boolean;
```

The Modernizr [prefixed docs](http://modernizr.com/docs/#prefixed) state that it returns a string

**Comment by vvakame** [comment]
@iambacon please send pull request. I'll review it.

**Comment by chrilith** [comment]
Hi,

It also may return a boolean if the prop is not found, or a function or object for DOM feature.

So "any" should be the way to go.

Thanks
