### ISSUE TITLE
D3 BubbleChart - The GraphNode values are optional

### ISSUE THREAD

**Issue by dani-h** [borisyankov/DefinitelyTyped#3734]
Here's an example by Mike Bostock on the bubble chart.
http://bl.ocks.org/mbostock/4063269#flare.json

When trying to implement it I saw that the datatype passed in, the graphnode, required all the attributes to be present. This isn't the case in Mike's example and it makes me wonder if all of the attributes are really necessary. There are a few core ones, but I think most are optional or calculated by d3 itself.

```
        export interface GraphNode  {
            id: number;
            index: number;
            name: string;
            px: number;
            py: number;
            size: number;
            weight: number;
            x: number;
            y: number;
            subindex: number;
            startAngle: number;
            endAngle: number;
            value: number;
            fixed: boolean;
            children: GraphNode[];
            _children: GraphNode[];
            parent: GraphNode;
            depth: number;
        }
```

**Comment by vvakame** [comment]
@dani-h please send pull request. I'll review it.

**Comment by dani-h** [comment]
@vvakame  #3775

**Comment by leemicw** [comment]
@vvakame it looks like the pull request was merged.  Can this issue be closed?
