### ISSUE TITLE
angular animate toast: Property 'position' does not exist on type 'MDSimpleToastPreset'.

### ISSUE THREAD

**Issue by PrashantAshok** [borisyankov/DefinitelyTyped#3882]
As per the ng animate toast (docs) [https://material.angularjs.org/#/demo/material.components.toast], this is valid code to show a simple modal. 

`
$mdToast.show(
      $mdToast.simple()
        .content('Simple Toast!')
        .position($scope.getToastPosition())
        .hideDelay(3000)
    );
`
but TypeScript throws the error. 

`
constructor(private $mdToast: ng.material.MDToastService) {
      var vm = this;
}
`
`
this.$mdToast.show(
       this.$mdToast.simple()
             .content("Hello World")
             .position("top right")
       );
`

**Comment by vvakame** [comment]
@PrashantAshok please send a PR. I'll review it.
