### ISSUE TITLE
Split up angular-ui into angular-ui-router and angular-ui-sortable

### ISSUE THREAD

**Issue by johnnyreilly** [borisyankov/DefinitelyTyped#3910]
Hi @michelsalib @jjeffery @santialbo @panuhorsmalahti @basarat @mattyork @thetallweeks @ofirgeller @gregwebs @cmc19 @vvakame @Bartvds 

I was wondering if it might be a good idea to break out the [angular-ui](https://github.com/borisyankov/DefinitelyTyped/tree/master/angular-ui) typings into angular-ui-router and angular-ui-sortable?  [UI-Bootstrap](https://github.com/borisyankov/DefinitelyTyped/tree/master/angular-ui-bootstrap) appears to already be following this convention and given the distinct nature of the various angular-ui projects I think it's the more sensible approach.

Would anyone have any objections?

**Comment by santialbo** [comment]
Seems a good idea, I like one-to-one relationships between typings and a bower/npm packages.

**Comment by michelsalib** [comment]
Right by me also

**Comment by johnnyreilly** [comment]
Thanks - I might give it a go then.  @santialbo I'll try and keep the 1-2-1 relationship as you suggest (I too :heart: bower)

**Comment by jjeffery** [comment]
+1 from me
