### ISSUE TITLE
Request to generate definitely typed script for jquery.window.js

### ISSUE THREAD

**Issue by narayannr84** [borisyankov/DefinitelyTyped#3958]
Hi,
In my project I am trying to use jquery.window.js for creating window widgets. But I could not find definitely typed script file. could you please generate a typed script file for jquery.window or let me know how to generate the definitely typed file for jquery window.

Regards
Narayan.NR

**Comment by ryan-codingintrigue** [comment]
I wouldn't mind having a go at this, the docs look very good. Just to confirm, this is the same library:
https://github.com/fglueck/jquery-window?

**Comment by ryan-codingintrigue** [comment]
I've submitted a PR for this:
https://github.com/borisyankov/DefinitelyTyped/pull/4045

**Comment by vvakame** [comment]
:+1:
