### ISSUE TITLE
mongoose Model<T> extends EventEmitter

### ISSUE THREAD

**Issue by hohl** [borisyankov/DefinitelyTyped#3968]
Due to the documentation of Mongoose.JS their `Model<T>` implementation extends `EventEmitter`. I'm successfully utilizing this behavior in my application. However the `Model<T>` of Mongoose.JS in this repository doesn't extend `EventEmitter`. It would be great if this could be added since it would by only line needed to be changed and it wouldn't even break current applications which use that `*.d.ts` file.

**Comment by horiuchi** [comment]
@hohl Please, send PR about this issue.

Of course, I think Model<T> should extend EventEmitter too. via: http://mongoosejs.com/docs/api.html#model_Model

**Comment by hohl** [comment]
done - see #3970
