### ISSUE TITLE
jquery.d.ts and SVG

### ISSUE THREAD

**Issue by ianitor** [borisyankov/DefinitelyTyped#3969]
Hi,
I'm using jQuery to modify SVG elements. Accessing elements by using the array accessor or get are not working in TypeScript because of compile errors, althrough it is working in jQuery.

I think, that the return types of following member should be changed to "Element" (SVG and HTML elements derive from Element). 

JQuery.get(index: number): HTMLElement;
JQuery.[index: number]: HTMLElement;

But this change would result to type errors, so I think the best solution would be:
JQuery.get(index: number): any;
JQuery.[index: number]: any;

What other users think?

**Comment by vvakame** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
I'm inclined to say "no" as I don't think providing `any` is to useful to users. That said I'd be up for the `Element` change if it could be made to work. It seems to be API compliant (which is our goal) http://api.jquery.com/get/

Would union types help here? Have `get` return Element or HTMElement?

**Comment by ianitor** [comment]
Of course Element would be the correct solution. But it would be a breaking change - that means existing code that uses get or the index accessor may have to be changed (e. g. Element does not provide property "style" or "getAttribute"). Also union types would result to the same effect, because only member are available that are defined in both types.

I agree that "any" is not useful to users, so there are three options:
1) Change to Element => breaking change
2) Change to HTMLElement|SVGElement => breaking change
3) Leave it as it is => SVG Elements are not really usable with Typescript and SVG.

What you think?

**Comment by johnnyreilly** [comment]
I don't think 1. is a great option for I

1 doesn't seem a useful option particularly as it would definitely break other peoples code.  Ironically it's the *technically* the most correct option but that doesn't lead me to favour it on this occasion.

2 sounds like the best option available.  How "breaking" a change would it be?  If you submitted that change as a PR you'd also have to take responsibility for fixing any changes to other typings that were affected before we could merge it.  That aside - would it actually be a breaking change to users then?  If they were coding assuming that `HTMLElement` was returned that code should still work I think?

What do other people think?  @basarat @vvakame @borisyankov @Bartvds ....

**Comment by ianitor** [comment]
With "breaking change" I meant a breaking change for other users, because e. g. clearAttributes() or "style" is not existing at SVGElement. The code won't compile any more when HTMLElement was assumed and member from that type are used...

**Comment by basarat** [comment]
I would love to have 2 as well. But as pointed out by @ianitor it is a breaking change: 

```ts
var foo : HTMLElement;
foo.clearAttributes();

var bar : HTMLElement | SVGElement;
bar.clearAttributes(); // Error
```

**Comment by basarat** [comment]
I don't think its going to be possible.

**Comment by johnnyreilly** [comment]
I agree with @basarat.  I think it might be best for you to fork `jQuery.d.ts` for your own purposes.  For what it's worth the jQuery typing is essentially "done".  It covers all of the jQuery official API as far as I know  Also, jQuery doesn't appear to be adding new features anymore - for the most part it seems to be focussed on ensuring that it works with all available browsers.  

That being the case I don't think you lose anything by forking - it's unlikely to change a great deal more.

@basarat / @vvakame - assuming @ianitor creates his own `jquery-svg.d.ts` what would you think to that living in DefinitelyTyped in a separate folder (say "jQuery-SVG")?  That would allow other people simple access to a common `jquery-svg.d.ts` file without breaking the existing code...

**Comment by basarat** [comment]
> jquery-svg.d.ts what would you think to that living in DefinitelyTyped in a separate folder (say "jQuery-SVG")? That would allow other people simple access to a common jquery-svg.d.ts file without breaking the existing code

No from me. Don't want to confuse `tsd install jquery` or others.  

To make it easier for people to create `jquery-svg`  we could add :

```ts
interface JQueryElement extends HTMLElement{}
```

And then just use `JQueryElement` instead of `HTMLElement` where you see fit.

**Comment by basarat** [comment]
Coincidently I was just using jquery with svg element. 

Its not *safe* e.g. something as simple as `addClass` will not work and fail silently: http://stackoverflow.com/a/10257755/390330

**Comment by johnnyreilly** [comment]
Well I think that rather settles it!

**Comment by ianitor** [comment]
Sorry, but I think that was a little bit hasty. Yes, "addClass" is missing, but there are documented options to solve that issue. We work with jQuery.SVG Plug-In (http://keith-wood.name/svg.html) to create, modifiy and query DOM objects with jQuery.(SVG) and it works damn good.

Apart from this, I will create a fork of jquery.d.ts, because it is really a special use case we use. It is a very gaphic based plattform. 

Thanks for the discussion!

**Comment by johnnyreilly** [comment]
:+1:
