### ISSUE TITLE
tsc with node.d.ts is giving error TS1005: ';' expected.

### ISSUE THREAD

**Issue by kevinpas** [borisyankov/DefinitelyTyped#4004]
I don't see what version of tsc you support so this might be a version problem:

error.ts
/// &lt;reference path="node.d.ts" /&gt;

> tsc error.ts
node.d.ts(101,36): error TS1005: ';' expected.
node.d.ts(690,23): error TS1005: ';' expected.
node.d.ts(702,23): error TS1005: ';' expected.
node.d.ts(1228,36): error TS1005: ';' expected.
> tsc
Version 1.0.3.0

**Comment by vvakame** [comment]
@kevinpas DefinitelyTyped is only supported latest tsc version.
please try with tsc 1.4.1.

**Comment by JDiPierro** [comment]
I'm getting this with all the latest versions (afaik)

    $ grunt
    Running "typescript:base" (typescript) task
    >> typings/cookie-parser/cookie-parser.d.ts(11,15): error TS1005: ';' expected.
    >> typings/cookie-parser/cookie-parser.d.ts(11,16): error TS1005: ';' expected.
    >> typings/node/node.d.ts(122,29): error TS1005: ';' expected.
    >> typings/node/node.d.ts(122,32): error TS1005: ',' expected.
    >> typings/node/node.d.ts(129,24): error TS1005: ',' expected.
    >> typings/node/node.d.ts(129,33): error TS1005: ';' expected.
    >> typings/node/node.d.ts(137,22): error TS1005: ',' expected.
    >> typings/node/node.d.ts(137,41): error TS1109: Expression expected.
    >> typings/node/node.d.ts(137,50): error TS1005: ';' expected.
    >> typings/node/node.d.ts(149,16): error TS1005: ',' expected.
    >> typings/node/node.d.ts(149,40): error TS1109: Expression expected.
    >> typings/node/node.d.ts(149,49): error TS1005: ';' expected.
    >> typings/node/node.d.ts(153,17): error TS1005: ',' expected.
    >> typings/node/node.d.ts(153,31): error TS1005: ',' expected.
    >> typings/node/node.d.ts(153,40): error TS1005: ';' expected.
    >> typings/node/node.d.ts(154,1): error TS1128: Declaration or statement expected.
    Warning: Task "typescript:base" failed. Use --force to continue.

    Aborted due to warnings.

----

    $ tsc -v
    message TS6029: Version 1.4.1.0

    $ npm -v
    2.14.7

    $ node -v
    v4.2.1

    $ tsd --version
    >> tsd 0.6.5

**Comment by vvakame** [comment]
The latest version of tsc is 1.6.2 now. please upgrade your tsc.

**Comment by JDiPierro** [comment]
I actually resolved this by switching from the `grunt-typescript` plugin to the `grunt-ts` plugin.. not sure what they do different but I stopped getting these errors with `grunt-ts`.

**Comment by piyushchauhan2011** [comment]
It's the same issue with `gulp-typescript` plugin too :disappointed:

**Comment by siddharthjain210** [comment]
I am getting this error with grunt-ts.

**Comment by askingalot** [comment]
I'm no expert on typescript or *.d.ts files, but I think line 122 of node.d.ts should be changed from 

```javascript
isBuffer(obj: any): obj is Buffer;
```
to
```javascript
isBuffer(obj: any): boolean; 
```

**Comment by paulomorgado** [comment]
+1

**Comment by danny8002** [comment]
you should exclude some folders from tsc building to **avoid **to compile *.d.ts files.
in my project i use **grunt-ts **instead of grunt-typescript which do not support excluding folders.

for example:

	grunt.initConfig({
		ts: {
			default: {
				src [**/*.ts,!**/*.d.ts,!node_modules/**/*.ts,!wwwroot/**/*.ts],
				options: {your options in here}
			}
		}
	});

and it works!

**Comment by sonalsavaratkar** [comment]
I have typescript version 1.8.10. though am getting the same error.

**Comment by wcomartin** [comment]
bump

**Comment by chief10** [comment]
bump

**Comment by jorgecasariego** [comment]
The same here with 1.8.10

**Comment by proudmonkey** [comment]
any updates on this guys? I've been playing around with Angular 2 RC 4 and I'm getting the same errors. I've spent almost 3 days try to fix things out but to no avail.

Details:
Windows 8.1
VStudio 2015 Update 3
Node 6.3.1
NPM 3.10.3
typescript 1.8.10
Gulp 3.9.1
gulp-typescript 2.13.6

Any suggestion is very much appreciated.  Thanks. :)

**Comment by danny8002** [comment]
the key point is **not compiling *.d.ts** no matter which typescript version you use. in your project, you should exclude all of the *.d.ts compilation to get rid of this issue.

**Comment by nicky-lenaers** [comment]
Still having this issue with 1.8.10 and gulp-typescript. Also on 2.0.0. Ignoring all the ``d.ts`` files, still doesn't work

**Comment by proudmonkey** [comment]
@nicky,

The fix for me was to exclude the folders that contain the .ts files in tsconfig.json. For example:

 "exclude": [
    "node_modules",
    "wwwroot",
    "Scripts/app"
  ]

The "Scripts/app" contains all my typescript files for angular 2.

**Comment by marclawson3** [comment]
@proudmonkey I am still struggling with this issue after 2 days now.  I am just trying to setup the basic 'hello world' Angular2 app in ASP.Net Core 1.0.

My config...

Windows 7 (also tried on Windows 8)
VStudio 2015 Update 3
TypeScript 1.8.6.0 (latest)
Node 4.5.0
NPM 3.10.7

I am using tsc.exe from C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8 and not gulp-typescript.  Should I change that?

My project is basically the Angular2 'hello world' app running on ASP.Net Core 1.0.  It takes 5 minutes to set it up from the Angular Quickstart guide and immediately throws bunches of errors.

package.json:
`{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.7",
    "@angular/compiler": "2.0.0-rc.7",
    "@angular/core": "2.0.0-rc.7",
    "@angular/forms": "2.0.0-rc.7",
    "@angular/http": "2.0.0-rc.7",
    "@angular/platform-browser": "2.0.0-rc.7",
    "@angular/platform-browser-dynamic": "2.0.0-rc.7",
    "@angular/router": "3.0.0-rc.3",
    "@angular/upgrade": "2.0.0-rc.7",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.21",
    "angular2-in-memory-web-api": "0.0.19",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.2",
    "typescript": "^1.8.10",
    "typings": "^1.3.2"
  }
}`

tsconfig.json:
`{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "./node_modules"
  ]
}`

(PS - I have tried dozen of combinations of 'exclude' options, but this is due to how the 'moduleResolution' parameter works - it still scans every file in node_modules regardless of what is in 'exclude')

typings.json:
`{
  "globalDependencies": {
    "core-js": "registry:dt/core-js#0.0.0+20160725163759",
    "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
    "node": "registry:dt/node#6.0.0+20160909174046"
  }
}`

Can anyone help?  I am dying here.  Haven't had my butt kicked like this for years now. :-(

![image](https://cloud.githubusercontent.com/assets/6473961/18515212/911352b2-7a62-11e6-9738-a25c8fa803aa.png)

**Comment by proudmonkey** [comment]
@marclawson3 Please check my article on Angular 2 here. http://www.codeproject.com/Articles/1124864/ASP-NET-Core-and-Angular-Code-Venture-Part

**Comment by marclawson3** [comment]
Thank you!

I also got some good info from:

http://blogs.u2u.be/peter/post/2016/08/16/building-the-angular-io-quickstart-with-asp-net-core.aspx

At least, I got this basic Angular project to build.

I appreciate your help!

**Comment by marclawson3** [comment]
@proudmonkey Great article.  This definitely helped get me up and running.  Well-done!

**Comment by Jeslopov** [comment]
I have the same problem but im getting it from the *.d.ts files inside the folders of the node_packages im using (like rxjs).

Im using  Visual Studio 2015 update3 and TypeScript 2.0.5

Please any Ideas??, thanks

**Comment by danny8002** [comment]
please try to use tsconfig.json in your project to control which files are compiled by tsc to get escape from this issue.

**Comment by Jeslopov** [comment]
thanks, problem solved. :)

**Comment by conecttasoftwares** [comment]
@Jeslopov hello, can you show me your tsconfig.json? I have same issue.

Thanks

**Comment by Jeslopov** [comment]
For me the problem was that even when i installed ts 2.0.5 y had in my project.cs typescript version 1.8
I only added the "typeRoots" property and changed the ts version in the project
now the file looks like this.

`{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "ES5", 
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "node_modules",
    "typings/main", //these two are forn not getting duplicate ts files definitions
    "typings/main.d.ts"
  ]
}`
hope this helps

**Comment by robinspark** [comment]
I fixed this error by renaming my React component file from .ts to .tsx

**Comment by a-eid** [comment]
solution for me was to use `export` not `export default` which is super weird I know ..

**Comment by exenone** [comment]
npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.3.0/bin/node" "/home/ubuntu/.nvm/versions/node/v6.3.0/bin/npm" "run" "tsc"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ng2-fundamentals-demo@1.0.0 tsc: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ng2-fundamentals-demo@1.0.0 tsc script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-fundamentals-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-fundamentals-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-fundamentals-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by exenone** [comment]
error is coming from 
app/app.module.ts(2,21): error TS1005: ',' expected.
app/app.module.ts(2,28): error TS1005: ',' expected.

**Comment by exenone** [comment]
any one please geive me a solution

**Comment by a-eid** [comment]
I posted one above ur first commit , try it

**Comment by exenone** [comment]
/home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:47391
                throw e;
                ^

TypeError: Cannot read property 'kind' of undefined
    at Object.getSynthesizedClone (/home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:8258:36)
    at addExportMemberAssignment (/home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:38338:85)
    at visitClassDeclaration (/home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:38418:17)
    at visitor (/home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:38184:28)
    at Object.visitNodes (/home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:35020:48)
    at transformCommonJSModule (/home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:38108:40)
    at transformSourceFile (/home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:38092:31)
    at /home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:896:86
    at reduceLeft (/home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:650:30)
    at /home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:896:42
    at transformSourceFile (/home/ubuntu/workspace/node_modules/typescript/lib/tsc.js:42737:20)

npm ERR! Linux 4.9.17-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.3.0/bin/node" "/home/ubuntu/.nvm/versions/node/v6.3.0/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-fundamentals-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run server" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-fundamentals-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-fundamentals-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by aleksander351** [comment]
@proudmonkey I have the folders excluded, but the d.ts errors inside node_modules still persist.

"exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]

**Comment by abhimanyuvaishy** [comment]
it's typescript compiler problem. just replace 'let' with 'var' then error disappear. but it is not a proper solution.

**Comment by sarathkumar1** [comment]
any one please help me..

Issue:- 
Source/app.ts <10,20>: error TS1005: `:` expected 
Source/app.ts <10,28>: error TS1005: `:` expected 
Source/app.ts <10,40>: error TS1005: `:` expected 
Source/app.ts <21,10>: error TS1005: `=` expected

**Comment by sarathkumar1** [comment]
all ts file are giving this error. I am using typescript version 2.6.1

**Comment by sarathkumar1** [comment]
any pleases give me solution
(myObject as this)
 I ma getting typescript compiler with as keyword

**Comment by mhegazy** [comment]
> all ts file are giving this error. I am using typescript version 2.6.1

The error suggests you are not really using 2.6. Lookup where your build is getting tsc from, and verify its version.

**Comment by SivaPrasanna45** [comment]
ts(110,33): error TS1005: ';' expected. 
This is what I am getting in my component.ts 
![image](https://user-images.githubusercontent.com/27672770/35966983-7d2af96e-0ce5-11e8-97a0-3bbfa03e0416.png)

**Comment by TwitchBronBron** [comment]
I realize this is a bit after the fact, but what @mhegazy said was what fixed my issue. My GLOBAL version of typescript was old, and that's where my "tsc" command was being executed from. Once i upgraded my global version, the errors went away.

**Comment by NewSonu** [comment]
Comment following in tsconfig.json file "skipDefaultLibCheck": true

**Comment by chandrababu-1994** [comment]
ERROR in src/app/app.component.ts(27,15): error TS1005: ':' expected.
src/app/app.component.ts(27,16): error TS1109: Expression expected.
src/app/app.component.ts(27,28): error TS1109: Expression expected.
src/app/app.component.ts(27,29): error TS1109: Expression expected.
src/app/app.component.ts(27,53): error TS1109: Expression expected.
src/app/app.component.ts(27,70): error TS1109: Expression expected.
src/app/app.component.ts(28,26): error TS1005: ':' expected.
src/app/test/test.module.ts(16,3): error TS1005: ',' expected.

kindly help it

**Comment by webhacking** [comment]
Set `skipLibCheck: true` in your tsconfig.json

**Comment by KR1470R** [comment]
> Set `skipLibCheck: true` in your tsconfig.json

Did not help :\

**Comment by ariv803** [comment]
Adding to tsconfig.json:   
` "skipLibCheck": true` and  `"exclude": ["**/*.test-d.ts", "**/*.d.ts"]`
helped.

**Comment by Hardhik** [comment]
@KR1470R 
So, this same issue had been bothering me for a long time and I resolved by simple upgrading my gulp-typescript version from
`^5.0.0-alpha.3` to `^5.0.1` and the typescript version from `^2.9.2` to `^4.1.3` in my project and that got rid of these errors.

**Comment by alanionita** [comment]
Had similar issues on Ubuntu. 

In my case I had installed `node-typescript` using apt 

To check this run 

```
sudo apt list --installed | grep -i node
```

Seems like that apt package is still using Typescript v2.7 and that was triggering the issues above

Once you remove that package your npm global / local typecript version will be used

```
sudo apt remove node-typescript
```

No issues with v4.2.4

**Comment by Unsleeping** [comment]
`"typescript": "4.9.3"`
solved for me
