### ISSUE TITLE
#3851 broke angular-ui-router and angular-translate definitions

### ISSUE THREAD

**Issue by pocesar** [borisyankov/DefinitelyTyped#4035]
On Typescript 1.4, the project won't compile anymore, since it's using the ng namespace not the angular module as per PR #3851 (from their bower package, inside the api folder in https://github.com/angular-ui/ui-router/tree/master/api)

```
G:/www/neuro/public/js/angular-ui-router/api/angular-ui-router.d.ts(31,38): error TS2304: Cannot find name 'IServiceProvider'.
G:/www/neuro/public/js/angular-ui-router/api/angular-ui-router.d.ts(49,42): error TS2304: Cannot find name 'IServiceProvider'.
G:/www/neuro/public/js/angular-ui-router/api/angular-ui-router.d.ts(82,63): error TS2304: Cannot find name 'IPromise'.
G:/www/neuro/typings/angular-translate/angular-translate.d.ts(36,85): error TS2305: Module 'ng' has no exported member 'IPromise'.
G:/www/neuro/typings/angular-translate/angular-translate.d.ts(37,87): error TS2305: Module 'ng' has no exported member 'IPromise'.
G:/www/neuro/typings/angular-translate/angular-translate.d.ts(47,36): error TS2305: Module 'ng' has no exported member 'IPromise'.
G:/www/neuro/typings/angular-translate/angular-translate.d.ts(51,27): error TS2305: Module 'ng' has no exported member 'IPromise'.
G:/www/neuro/typings/angular-translate/angular-translate.d.ts(57,42): error TS2305: Module 'ng' has no exported member 'IServiceProvider'.
G:/www/neuro/typings/angularjs/angular.d.ts(17,1): error TS2440: Import declaration conflicts with local declaration of 'ng'
```

**Comment by a3chic9** [comment]
I've started running into a similar issue. Most of my issues seem to be related to that last error

> Import declaration conflicts with local declaration of 'ng'

**Comment by zuzusik** [comment]
Created the PR that fixes the issue: https://github.com/borisyankov/DefinitelyTyped/pull/4055

**Comment by kenhowardpdx** [comment]
In case anyone else runs into this...

Depending on your installation of `angular-ui-router` you may already have a definition file included in the project which is outdated [source](https://github.com/angular-ui/ui-router/blob/master/api/angular-ui-router.d.ts)

The definition file in DefinitelyTyped should be used instead. Be sure to disable compilation of the outdated file in your IDE.

**Comment by xtv** [comment]
In case anyone still has the issue.. i got angular-scenario-1.2 automatically installed which causes the same issue.. remove that, works

**Comment by pocesar** [comment]
doing `tsd install angularjs/` installs everything and break things.
