### ISSUE TITLE
Leaflet LatLngBounds

### ISSUE THREAD

**Issue by jplante** [borisyankov/DefinitelyTyped#4036]
There are 4 missing methods from the Leaflet.d.ts file for the L.LatLngBounds class:

getNorth(): number
getSouth(): number
getWest(): number
getEast(): number

http://leafletjs.com/reference.html#latlngbounds

Thanks,
Jason

**Comment by jplante** [comment]
/**
		 * Returns the west longitude in degrees of the bounds.
		 */
		getWest(): number;

		/**
		 * Returns the east longitude in degrees of the bounds.
		 */
		getEast(): number;

		/**
		 * Returns the north latitude in degrees of the bounds.
		 */
		getNorth(): number;

		/**
		 * Returns the south latitude in degrees of the bounds.
		 */
		getSouth(): number;

**Comment by vvakame** [comment]
@jplante please send a PR. I'll review it.

**Comment by jplante** [comment]
Yes, now is the time to demonstrate my ignorance.  I will create a PR once I know what that is.

**Comment by jplante** [comment]
Right, so PR = Pull Request.  Will do that soon.

**Comment by vvakame** [comment]
via #4099
