### ISSUE TITLE
highcharts.d.ts

### ISSUE THREAD

**Issue by ptcc2000** [borisyankov/DefinitelyTyped#4063]
interface HighchartsSeriesObject {
visible: number;
}
visible: boolean;

**Comment by johnnyreilly** [comment]
Pull requests gratefully received :smile:

**Comment by baltie** [comment]
PR #5226 fixes this, among some other things. Hopefully eventually merged. :)

**Comment by johnnyreilly** [comment]
Merged!

Date: Thu, 6 Aug 2015 22:44:28 -0700

**Comment by baltie** [comment]
Thanks. I deleted the comment since I discovered that someone else had made that change earlier. I had fixed it for the other places visible still were defined as string.

Thanks for merging! :)
