### ISSUE TITLE
Jasmine pending() accepts string argument

### ISSUE THREAD

**Issue by a3chic9** [borisyankov/DefinitelyTyped#4108]
According to the [Jasmine 2.2 docs](http://jasmine.github.io/2.2/introduction.html#section-Pending_Specs) the `pending()` function should accept a string for a reason. I assume this is an optional parameter.

````javascript
  it("can be declared by calling 'pending' in the spec body", function() {
    expect(true).toBe(false);
    pending('this is why it is pending');
  });
````

**Comment by a3chic9** [comment]
working on a PR

**Comment by vvakame** [comment]
via #4109
