### ISSUE TITLE
Is `require` necessary at the bottom of marionette.d.ts ?

### ISSUE THREAD

**Issue by pligor** [borisyankov/DefinitelyTyped#4151]
At the bottom of `marionette.d.ts` file there is this segment of code:
```
declare module 'backbone.marionette' {
    import Backbone = require('backbone');

    export = Marionette;
}
```
Is require necessary? Because we are trying to avoid requirejs in the web browser for the time being.

*I know having to insert `<script ...` statements in `index.html` of an single page application is tedious but if you know any good tutorial that will take us without troubles from inserting .js files to including them using requirejs then you are more than welcome to share it*
Thank you!

**Comment by vvakame** [comment]
@pligor Marionette is visible from anywhere. https://github.com/borisyankov/DefinitelyTyped/blob/master/marionette/marionette.d.ts#L126
external module definitions is required if you want to use require.js or browserify.

**Comment by pligor** [comment]
You are correct. That is a little strange that the require statement is not executed or does not seem to be executed in the module declaration. Other than that if we call `require(...)` anywhere else in the code and we are not including requirejs library then there is an error in javascript in runtime.  
Anyway it seems to work fine for now so thanks for taking the time to consider our issue.
