### ISSUE TITLE
grunt.d.ts: Type of cwd in interface IExpandedFilesConfig is wrong

### ISSUE THREAD

**Issue by callmetango** [borisyankov/DefinitelyTyped#4207]
`cwd?: boolean` in interface IExpandedFilesConfig is typed as boolean. According to the [API documentation of grunt.file.expand] (http://gruntjs.com/api/grunt.file#grunt.file.expand) this should be a path string.

Shall I create a fork and pull request for the fix?

**Comment by vvakame** [comment]
@callmetango yep, I'll review it.
