### ISSUE TITLE
Use EditorConfig files to encourage/assist in resolving whitespace inconsistencies

### ISSUE THREAD

**Issue by jedmao** [borisyankov/DefinitelyTyped#4211]
I suggest using [EditorConfig](http://editorconfig.org/) to encourage/assist with whitespace inconsistencies throughout this project. @Bartvds already [spoke out](https://github.com/borisyankov/DefinitelyTyped/issues/1569#issuecomment-35524237) about how [we can't all agree on indentation settings](https://github.com/borisyankov/DefinitelyTyped/issues/1709), so those would be set in their respective sub-directories.

At the project root, we can have the following settings:
```ini
root = true

[*.ts]
trim_trailing_whitespace = true
insert_final_newline = true
```

Then, in each respective folder, they can have their own indentation settings without `root = true`, which means the root settings apply to all sub-directories, but not the other way around, like so:

```ini
[*.ts]
indent_style = tab
```

Or for spaces:

```ini
[*.ts]
indent_style = space
indent_size = 4
```

This ensures we're not stepping on anybody's toes.

**Comment by cliffburger** [comment]
Thanks for removing this from the pull request.

**Comment by vvakame** [comment]
:+1: 

I like this style. it is VisualStudio's default. (isn't it?)

```
root = true

[*.ts]
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 4
```

**Comment by jedmao** [comment]
@vvakame I like tabs, so it's the age-old war. If you like the configuration you've specified, all you have to do is add the following to the sub-folders you submit to DefinitelyTyped:

```ini
[*.ts]
indent_style = space
indent_size = 4
```

Since `root = true` isn't defined, EditorConfig will keep looking up the folder structure until it finds an .editorconfig file with `root = true`, which it would at the project root. This means your configuration will be merged with the one at the project root, resulting in your exact configuration.

Make sense?

**Comment by jedmao** [comment]
@vvakame BTW you can use `ini` as the file format for code coloration in EditorConfig files on GitHub.

**Comment by vvakame** [comment]
:+1:

**Comment by davidreher** [comment]
I would propose to use 2 spaces as done in the [airbnb/javascript](https://github.com/airbnb/javascript) styleguide ...
