### ISSUE TITLE
Wrong function signature for argument to underscore's reduce.

### ISSUE THREAD

**Issue by dbeckwith** [borisyankov/DefinitelyTyped#4244]
Underscore's `reduce` function takes a function that according to underscore's doc (http://underscorejs.org/#reduce) should take the memo, then the current value, then either the current index or the current key, depending on whether the list was a list or a dictionary. But in `underscore.d.ts` the dictionary version of `reduce` takes an `ObjectIterator` as the function type, which has no memo argument. `MemoIterator` is used correctly for the array version, I think there just needs to be like a `MemoObjectIterator` for the dictionary case.

**Comment by vvakame** [comment]
@dbeckwith please send a PR. I'll review it.
