### ISSUE TITLE
node.d.ts: interface Global / NodeJS.Global breaks current Node+TypeScript

### ISSUE THREAD

**Issue by chbrown** [borisyankov/DefinitelyTyped#4249]
TypeScript complains of missing names in the new `interface Global` type, from 5235188 (5 days ago).

    tsc --module commonjs --target ES5 --declaration my_incredible_new_mvc_framework.ts
    node/node.d.ts(198,26): error TS2304: Cannot find name 'DataView'.
    node/node.d.ts(212,21): error TS2304: Cannot find name 'Map'.
    node/node.d.ts(221,21): error TS2304: Cannot find name 'Set'.
    node/node.d.ts(231,25): error TS2304: Cannot find name 'WeakMap'.

Those are all ES6 types. The current Node.js / v8 version implements them, but they aren't native types, as far as the TypeScript compiler is concerned. Perhaps we are getting ahead of ourselves here?

My system:

    $ node --version
    v0.12.2
    $ tsc --version
    message TS6029: Version 1.5.0-beta

**Comment by vvakame** [comment]
@chbrown please watching this PR. https://github.com/borisyankov/DefinitelyTyped/pull/4101

**Comment by lucasmciruzzi** [comment]
Is this fixed or there is a temporary fix to implement?

I'm still getting those same errors:
````
node.d.ts(198,26): error TS2304: Cannot find name 'DataView'.
node.d.ts(212,21): error TS2304: Cannot find name 'Map'.
node.d.ts(221,21): error TS2304: Cannot find name 'Set'.
node.d.ts(231,25): error TS2304: Cannot find name 'WeakMap'.
````

**Comment by chbrown** [comment]
@lucasmciruzzi I simply reverted the breaking commit in my DefinitelyTyped fork and it's been working great: https://github.com/chbrown/DefinitelyTyped/commit/17f99f1

**Comment by lucasmciruzzi** [comment]
Thanks for the reply @chbrown! I'm using DTSM so I don't get updates from forks, I only get them from the borisyankov repo. Shouldn't this fix be on the main repo?

**Comment by omencat** [comment]
@vvakame thanks for the headsup on https://github.com/borisyankov/DefinitelyTyped/pull/4101 . 
with typescript 1.5.2 ES5 target output resolves the DataView error. Map, Set, WeakMap are still present, but compile appears to work fine.

**Comment by sethx** [comment]
+1 to merge changes from chbrown to borisyankof repo.

**Comment by hsrobmln** [comment]
@chbrown Thank you for the quick fix, this solved my issue and works for now!

**Comment by aciccarello** [comment]
I updated the SHA in my `tsd.json` file to f0aa5507070dc74859b636bd2dac37f3e8cab8d1 and ran `tsd reinstall -o` to revert back to the prior version.

**Comment by drudru** [comment]
Thanks @chbrown - I switched to your repo until this gets fixed.

**Comment by lucasmciruzzi** [comment]
Why is this fix not merged with the repo yet? @chbrown @vvakame

**Comment by vvakame** [comment]
master/HEAD are solved this issue.

**Comment by lucasmciruzzi** [comment]
I'm still using the chbrown@17f99f1 version because the borisyankov version still trows errors with "Map", "Set" and "WeakMap" when target is ES5 ....

**Comment by chbrown** [comment]
@lucasmciruzzi no harm in that, but after @vvakame's comment, I tried out node.d.ts from DefinitelyTyped/master, which, combined with the typescript@1.5.3 that was released ~5 days ago, compiles just fine.

Are you getting those errors even with the latest `tsc`?

**Comment by lucasmciruzzi** [comment]
Yep, I'm running TypeScript v1.5.3

**Comment by lucasmciruzzi** [comment]
Fixed! ... it seems like it was a problem with the packages cache on my PC. Thanks a lot :)

**Comment by Kelvin-Ng** [comment]
I **don't** get any error when I run tsc in command line directly. However, I **do** get `error TS2304: Cannot find name 'DataView'.` when I use grunt. `GruntFile.js`:
```
...
		typescript: {
			base: {
				src: ['src/**/*.ts'],
				dest: 'build',
				options: {
					module: 'commonjs',
					target: 'es5'
				}
			}
		}
...
```

Using https://github.com/borisyankov/DefinitelyTyped/commit/f0aa5507070dc74859b636bd2dac37f3e8cab8d1 as stated by @aciccarello works.

TypeScript version is 1.5.3. Any ideas?

**Comment by lucasmciruzzi** [comment]
@Kelvin-Ng it should be an issue with the grunt plugin. It surely uses its own TypeScript instead of the globally installed. Check the settings of the plugin you are using for an option to set the TypeScript instance to use.

PS: If you can, move away from grunt to gulp, the plugin is far better: https://www.npmjs.com/package/gulp-typescript and has a "typescript" option to set a custom version of it.

**Comment by Kelvin-Ng** [comment]
@lucasmciruzzi

Thank you! I have moved to gulp and gulp-typescript works great. Thanks for your recommendation and I like gulp more than grunt now.

**Comment by vote539** [comment]
As of yesterday this is now fixed in grunt-typescript.

https://github.com/k-maru/grunt-typescript/issues/105
