### ISSUE TITLE
longDateFormat in moment is a function and not a property.

### ISSUE THREAD

**Issue by HarelM** [borisyankov/DefinitelyTyped#4257]
First and foremost great project!
I was trying to get moment work with this code:
```moment.localeData().longDateFormat.L``` but it didn't seem to work as ```longDateFormat``` is a function and not a property (I think).
this however, did work:```moment.localeData().longDateFormat("L").```

in short I suggest to change the following:
```longDateFormat?: MomentLongDateFormat;``` to ```longDateFormat(formatType: string): string;```

Thanks,
Harel M.

**Comment by vvakame** [comment]
@HarelM please send a PR. I'll review it.

**Comment by HarelM** [comment]
Please see: (this is my first pull request, I'm not sure that I followed the right steps).
https://github.com/HarelM/DefinitelyTyped/commit/36e3c3b7c9b1dc6d29083806266a6232464b6cc9

Thanks,
Harel M.

**Comment by DickvdBrink** [comment]
@vvakame I think this one is fixed?
