### ISSUE TITLE
export function getAllInWindow(windowId:number, callback?:(tab:Tab[]) => void):void;

### ISSUE THREAD

**Issue by kk80805588** [borisyankov/DefinitelyTyped#4258]
add 
 export function getAllInWindow(windowId:number, callback?:(tab:Tab[]) => void):void;

**Comment by vvakame** [comment]
@kk80805588 what library this is? please send a PR. I'll review it.

**Comment by kk80805588** [comment]
chrome extensions apis
https://developer.chrome.com/extensions/tabs

Please add getAllInWindow

chrome.tabs.getAllInWindow(integer windowId, function callback)

**Comment by joaope** [comment]
@kk80805588 @vvakame chrome.tabs.getAllInWindow() is deprecated.

Check here: https://developer.chrome.com/extensions/tabs#method-getAllInWindow

Consider closing this issue.

**Comment by vvakame** [comment]
@joaope thanks!
