### ISSUE TITLE
chrome.extension.onRequest.addListener

### ISSUE THREAD

**Issue by kk80805588** [borisyankov/DefinitelyTyped#4261]
add chrome.extension.onRequest.addListener()

**Comment by vvakame** [comment]
@kk80805588 please send a PR. I'll review it.

**Comment by kk80805588** [comment]
Please add
chrome.extension.onRequest.addListener

https://developer.chrome.com/extensions/extension

**Comment by joaope** [comment]
@kk80805588 @vvakame  chrome.extension.onRequest is deprecated.

Check here: https://developer.chrome.com/extensions/extension#event-onRequest

Consider closing this issue.

**Comment by vvakame** [comment]
@joaope thanks!
