### ISSUE TITLE
Branch request: tsc-1.5.0-beta

### ISSUE THREAD

**Issue by aarondandy** [borisyankov/DefinitelyTyped#4342]
I would like to submit a small change to auth0 from my branch but it applies to `1.5.0-beta` and not `-alpha`. Could a new branch be created for `tsc-1.5.0-beta`?

Branch: https://github.com/aarondandy/DefinitelyTyped/tree/tsc-1.5.0-beta-auth0-fix

**Comment by vvakame** [comment]
@aarondandy tsc-1.5.0-alpha branch is already using 1.5.0-beta. https://github.com/borisyankov/DefinitelyTyped/blob/tsc-1.5.0-alpha/package.json#L39
please send your change to 1.5.0-alpha branch.

**Comment by vvakame** [comment]
https://github.com/borisyankov/DefinitelyTyped/pull/4101

**Comment by aarondandy** [comment]
Done.
