### ISSUE TITLE
chai definitions are lacking `should`

### ISSUE THREAD

**Issue by AGBrown** [borisyankov/DefinitelyTyped#4372]
I have an [update for the chai definitions] <sup>†</sup> that add `should` support (both the [`should` fluent] method and the [`should` extras]).

The `chai-tests.js` file has ~460 `expect` tests. Do I need to replicate each of those as a `should` test in order to submit the PR?

<sup>†</sup> on branch [AGBrown//DefinitelyTyped-ABContrib/4372-chai-should]

[update for the chai definitions]: https://github.com/AGBrown/DefinitelyTyped-ABContrib/commit/2e1426a "AGBrown//DefinitelyTyped-ABContrib/2e1426a"
[AGBrown//DefinitelyTyped-ABContrib/4372-chai-should]: https://github.com/borisyankov/DefinitelyTyped/compare/master...AGBrown:4372-chai-should "PR compare for 4372-chai-should"
[`should` fluent]: http://chaijs.com/guide/styles/#should "chaijs > guide > styles > should"
[`should` extras]: http://chaijs.com/guide/styles/#should-extras "chaijs > guide > styles > should extras"

**Comment by vvakame** [comment]
@jedmao do you have any comment?

**Comment by AGBrown** [comment]
@vvakame, @jedmao, there is now an update to the `chai-tests.ts` file (using some regex jigger pokery I added a [`should` fluent] test for (hopefully) each `expect` test). Here is the [complete diff] of the additions. If this looks palatable then I can look to add in the tests for the [`should` extras]

I also rebased [AGBrown//DefinitelyTyped-ABContrib/4372-chai-should] onto the latest DefinitelyTyped master while I was at it.

I am currently using these chai.d.ts definitions in the work for [pouchdb.d.ts](https://github.com/AGBrown/pouchdb.d.ts) (reference #4328), so would rather get these right and updated in DefinitelyTyped before trying to commit anything for the `pouchdb.d.ts` file.

[commit f93c787]: https://github.com/AGBrown/DefinitelyTyped-ABContrib/commit/f93c787 "AGBrown//DefinitelyTyped-ABContrib/f93c787"
[complete diff]: https://github.com/AGBrown/DefinitelyTyped-ABContrib/compare/2259de6...AGBrown:f93c787 "Additions made to chai.d.ts and chai-tests.ts"
[AGBrown//DefinitelyTyped-ABContrib/4372-chai-should]: https://github.com/borisyankov/DefinitelyTyped/compare/master...AGBrown:4372-chai-should "PR compare for 4372-chai-should"
[`should` fluent]: http://chaijs.com/guide/styles/#should "chaijs > guide > styles > should"
[`should` extras]: http://chaijs.com/guide/styles/#should-extras "chaijs > guide > styles > should extras"

**Comment by AGBrown** [comment]
In fact while this has my attention I added the [`should` extras] tests anyway. I'll submit a PR and you can do with it as you will.

[`should` extras]: http://chaijs.com/guide/styles/#should-extras "chaijs > guide > styles > should extras"

**Comment by jedmao** [comment]
@AGBrown I remember having issues extending the `Object` prototype with TypeScript. For example, I tried this:
```ts
interface Object {
	should: Assertion;
}

interface Assertion {
	not: Assertion;
}

var foo: any = {};
foo.should; // No Intellisense
```
If you can figure out a way to fix that issue it would be awesome, but this is why the current chai definitions have the `expect` tests and not the `should` equivalents.

**Comment by AGBrown** [comment]
@jedmao You aren't wrong. It was going so well until I submitted PR #4398 and travis went red. What VS was happy with travis most certainly isn't. I'm moving to branch [AGBrown//DefinitelyTyped-ABContrib/4372-brew-chai] to stop spamming the main DT travis with red builds.

[AGBrown//DefinitelyTyped-ABContrib/4372-brew-chai]: https://github.com/AGBrown/DefinitelyTyped-ABContrib/tree/4372-brew-chai

**Comment by jedmao** [comment]
@AGBrown it's a lot easier if you try to get it to work on the [TypeScript Playground](http://www.typescriptlang.org/Playground/), conceptually, before waiting for a Travis CI build to fail

**Comment by AGBrown** [comment]
@jedmao Agreed - I've backed way off travis - VS lulled me into a false sense of "all is fine, push and pr". I'm using playground and DT locally with `npm test` for the moment.

I'm in irc://freenode.net/#typescript if you have time.

**Comment by AGBrown** [comment]
The build issues I had are now fixed by removing a conflicting `should` from [chai-subset.d.ts](https://github.com/AGBrown/DefinitelyTyped-ABContrib/commit/8fa7bd02f9db65c6d39ec82debed6c03297b8d3a#diff-2faf01fab0fa8d83fffe812879736a03). Hopefully the new chai.d.ts in the PR is [good to merge](https://github.com/borisyankov/DefinitelyTyped/pull/4398/files)

**Comment by rcollette** [comment]
+1   
But.. why are chai functions like expect() not declared globally as they are in the mocha.d.ts?   I have to modify all my existing unit tests to have `chai.expect` rather than just using `expect`

**Comment by AGBrown** [comment]
@rcollette. chai requires you to do this (see http://chaijs.com/guide/styles/):

```javascript
var expect = require('chai').expect;
```

So declaring `expect` globally in the d.ts won't help you - you still need to write that line in your .ts files or it won't appear in your js and your tests wouldn't work (if I understood your question properly).

**Comment by rcollette** [comment]
I'm using Karma with mocha, chai and sinon.  If I just create a plain js spec, I can write `expect(..)` without any require statements.   If I use TS, I wind up having to write `chai.expect(...)`, still without require statements.  I think the "frameworks" configuration option in Karma probably does some of this automatically?

**Comment by jedmao** [comment]
Why don't you try this?

```ts
declare var expect: typeof chai.expect;
expect(true).to.be.true;
```

**Comment by AGBrown** [comment]
@rcollette. Are you maybe using [karma-chai]? If so then it does the `expect` wire-up for you as you can see here: https://github.com/xdissent/karma-chai/blob/master/adapter.js

If that is the case you probably want to open a new ticket for a karma-chai.d.ts as I don't think there is one yet. You could even add it yourself and create a PR - it definitely isn't related to chai.d.ts though.

[karma-chai]: https://github.com/xdissent/karma-chai
