### ISSUE TITLE
Dat gui using Object instead of any?

### ISSUE THREAD

**Issue by SimoneGianni** [borisyankov/DefinitelyTyped#4438]
Sorry, first issue report here and don't know if there are any conventions about definitions that I'm missing.

I'm using the definition of dat-gui, which uses Object in many places. For example 

```
add(target: Object, propName:string): GUIController;
```

In theory an inline object is an Object in javascript, but seems like it is not the case in TypeScript, at least 1.4 that I'm using. This gives me error :

```
var obj = {a:1,b:1};
datgui.add(obj,'a');
```

However, obviously it's a valid use of dat-gui. It gives error also passing in other libraries stuff, like a THREE.Vector3 instance for example, which is one of the most common uses of dat-gui.

If I replace ":Object" with ":any" in dat-gui.d.ts it works, but will allow using non-objects, like strings or numbers.

Should the definition be changed? Or is my typescript version too old and doesn't deal with Object correctly? Or am I missing something else?

**Comment by vvakame** [comment]
ping @gyohk

**Comment by gyohk** [comment]
Thank you for the reporting.
I'll check the problem, so please wait several days.

**Comment by gyohk** [comment]
I'm sorry for the delay in my response.
Where I've tried, this definition seems to work fine even for object literal with TS v1.0.0, v1.4.0 and latest.

Please see #4504 .
