### ISSUE TITLE
Add angular2 Directive

### ISSUE THREAD

**Issue by adjohnson916** [borisyankov/DefinitelyTyped#4449]
Need to add type definition for [Angular 2 Directive class](https://angular.io/docs/js/latest/api/annotations/Directive-class.html).

**Comment by alexeagle** [comment]
Angular team is close to delivering a complete .d.ts for angular2, probably with the next alpha release. We'll push releases to definitely typed as well.

**Comment by alexeagle** [comment]
I have a working angular2.d.ts, but it requires typescript 1.5 so the tests for DT fail.
https://gist.github.com/alexeagle/c7e0b05927469666d703

**Comment by alexeagle** [comment]
I think this can be closed - https://github.com/borisyankov/DefinitelyTyped/pull/4563 is in
