### ISSUE TITLE
Update Angular Material to 0.9.6

### ISSUE THREAD

**Issue by matt-major** [borisyankov/DefinitelyTyped#4462]
The existing definition is for `0.9.0-rc1+` and the latest version of the library is `0.9.6`.

Could the definition please be updated to match?

**Comment by robertbaker** [comment]
Maybe I should file a separate issue but in MDPalette contrastDarkColors (and light) should be an array of strings not just a string.

**Comment by mtraynham** [comment]
@vvakame Close this one as well, #4845 brings angular-material version up to 0.10.1

**Comment by vvakame** [comment]
okay, thanks!
