### ISSUE TITLE
React 0.13.1 CreateElement - Error TS2345

### ISSUE THREAD

**Issue by dho825** [borisyankov/DefinitelyTyped#4472]
There are a few examples where extending React.Component<P,S>{...} whereby *if* the props specified by the parent do not exactly match the corresponding propTypes interface of the component, the resulting call to React.createElement(<component>, {}) throws this error: ```error TS2345: Argument of type 'typeof [some component name]' is not assignable to parameter of type 'string'.``` (DOMElement example, but similar errors occur with ReactElement, etc.)

I'm going to reference https://github.com/bparadie/fluxts-todomvc as it is basically a port of the Todo tutorial by Facebook.

In **TodoTextInput.react.jsx** you see that the main component extends ReactComponent (a wrapper extension over React.Component). If I understand correctly:
```
class TodoTextInput extends ReactComponent<any,TodoTextInputState> {

  static propTypes: React.ValidationMap<TodoState> =  {
    className: ReactPropTypes.string,
    id: ReactPropTypes.string,
    placeholder: ReactPropTypes.string,
    onSave: ReactPropTypes.func.isRequired,
    value: ReactPropTypes.string
  };
```
should be:
```
class TodoTextInput extends ReactComponent<TodoTextInputProps,TodoTextInputState> {

  static propTypes: React.ValidationMap<TodoTextInputProps> =  {
    className: ReactPropTypes.string,
    id: ReactPropTypes.string,
    placeholder: ReactPropTypes.string,
    onSave: ReactPropTypes.func.isRequired,
    value: ReactPropTypes.string
  };
```
But if you try to compile this, you will get the error stated above. This is (from my testing) due to the fact that the implementations of this in **Header.react.tsx** and **TodoItem.react.tsx** do not pass in ALL the props when rendering the component. 

I believe this rests in the implementation of ```React.createElement```. While simply replacing the actual interface with "any" allows the build without throwing the exception, it doesn't seem like the "TS way".

Is there a reason why TS throws this error when ALL the props are not specified? Even if they are optional, the compiler complains. It makes it useless to create a defaultProps property...

**Edit:** adding references to commiters: @vsiao , @ggarek , @jbrantly so (I think) they get a little notification...this repo is pretty broad, so hoping this helps narrow the focus to the key contributors to this section

**Comment by jbrantly** [comment]
I think this might be due to something I noticed with `createElement` as it's currently modeled but haven't had a chance to verify/fix yet. Basically I don't think TypeScript does a great job of matching up `ComponentClass<P>` with something like `class MyClass extends Component<P, S>`, I'm guessing due to the extra stuff like `propTypes`, etc. Try changing the definition where it currently is:
```
function createElement<P>(
        type: ComponentClass<P>,
        props?: P,
        ...children: ReactNode[]): ReactElement<P>;
```
to 
```
function createElement<P>(
        type: (props?: P, context?: any) => Component<P, any>,
        props?: P,
        ...children: ReactNode[]): ReactElement<P>;
```
and see if that helps.

**Comment by jbrantly** [comment]
I forgot to mention that you will also need to make the properties optional (looks like you tried that, but wanted to make sure you kept those optional when trying the above).

**Comment by dho825** [comment]
@jbrantly so I tried the above--which I'm guessing is trying to reimplement the createClass TopLevelAPI functions to fit the ```class MyClass extends...``` construct--and still no dice. 

Since rendering something like ```<TodoTextInput, {...}>``` is rendering a ReactElement vs a DOMElement, whereas before, the compiler was passing the component as a DOMElement (?). The error that results is something like: 
```error TS2345: Argument of type 'typeof TodoTextInput' is not assignable to parameter of type '(props?: { className: string; onSave: (text: string) => void; value: string; }, context?: any) =>...'.```

I've uploaded my version of the todomvc app (with my changes) to: https://github.com/dho825/fluxts-todomvc-test

Is this really an issue with the matching up ```ComponentClass<P>``` with something like ```class MyClass extends Component<P, S>``` as you mentioned above? 

I am new to TS so I'm still fairly green with how definition files work, but what you suggested *seems* like it should work...but somehow the component is not being recognized as any of the current interfaces: Component, ClassicComponent, or DOMElement. I'm going to continue testing around to a) get a better understanding of how the definitions work and b) try to figure out a way to fix this...

__Thanks in advance for anyone who can help or add additional context :)__

**Comment by jbrantly** [comment]
Ah, I was doing it from memory and I think I told you wrong. Try this:

```
function createElement<P>(
        type: { new(props?: P, context?: any): Component<P, any> },
        props?: P,
        ...children: ReactNode[]): ReactElement<P>;
```

**Comment by dho825** [comment]
@jbrantly Ugh. I apologize if I'm getting bothersome, but it still is giving me issues. I've actually stopped using the extended ReactComponent class and tried to keep it implementation as vanilla as possible.

What it seems like TS is doing is calling createElement as if the passed \<P\> was a DOMElement, hence the error regarding typeof Component is not assignable to param 'string'.

Even if I create this overload, it somehow passes over it...

This is my modified react.d.ts:

```
    function createElement<P>(
        type: {new (props?: P, context?: any): Component<P, any>},
        props?: P,
        ...children: ReactNode[]): ReactElement<P>;
    function createElement<P>(
        type: string,
        props?: P,
        ...children: ReactNode[]): DOMElement<P>;
    function createElement<P>(
        type: ClassicComponentClass<P> | string,
        props?: P,
        ...children: ReactNode[]): ClassicElement<P>;
    function createElement<P>(
        type: ComponentClass<P>,
        props?: P,
        ...children: ReactNode[]): ReactElement<P>;
```

**Comment by jbrantly** [comment]
I'll pull your version of the app later and try it out myself and see if I can't get it working. It currently displays the issue, right? 

Regarding error messages, it's useful to know that TS always reports the *first* overload as the error, even though it tried and failed with all of them. That can sometimes be confusing because you're like "of course it's not a string!".

**Comment by dho825** [comment]
Oh man, thanks for being patient with me and giving me some more insight
into TS error checking.

It was your TS+React presentation that convinced me to dive in to using TS.
The repo was hastily put together, but essentially if you run ```gulp
build``` you'll see the compiler complain.

**Comment by vsiao** [comment]
Totally agree that the error message could be a lot better. The thing with `ComponentClass<P>` is that it requires `P` to be consistent throughout, which means that `static` properties such as `defaultProps` always need to be explicitly type-annotated, or else the compiler will infer a `P` from `defaultProps` which is incompatible with the `P` provided by `React.Component`. Here's an example:

```ts
interface TimerProps extends React.Props<Timer> {
    initialTime?: number;
    endTime: number;
}
class Timer extends React.Component<TimerProps, {}> {
    static defaultProps = {
        initialTime: 0
    };
    ...
}
```

Notice that `defaultProps` has type `{ initialTime: number }`, which is incompatible with `TimerProps`. So `Timer` is no longer a valid `ComponentClass<P>`, and the overload resolution for `createElement` fails.

The downside of this, as you've already observed, is that you'll need to pass all of the required props as well (`null` should work just fine in most cases). This is a limitation of TypeScript's type system.

**Comment by dho825** [comment]
@vsiao Thank you for explaining how \<P\> is being passed around and how defaultProps messes around with the ```createElement``` overloads. But it seems that _all_ props, required or not, need to be passed. It's odd that even optional parameters will throw errors when not specified, with or without defaultProps. 

It seems like you will need to pass in all props (required or not) in JSX or React.createElement(...} regardless of defaultProps' ```P``` type. My current hypothesis is that the limitation to TS as aforementioned, is either (a) that TS does not have a way to check ```P``` type as it is being passed around to various functions or (b) that the definitions file is not properly passing it around...

Thoughts? 

P.S. thanks to **jbrantly** and **vsaio** for being patient with me and the help they provided. I'm just going to work around the current situation and not be so OCD about clearing the compiler of all errors =_="

See reference example below:

```
>>> file: mainApp.ts

///<reference path="../../libs/react.d.ts" />

import Example = require('./example');
import React = require('react');

React.render(
	(React.createElement(Example, {id: "uuid-1", className: "greenClass", hasValue: true})),
	document.getElementById('app')
);

>>> file: example.ts

///<reference path="../../libs/react.d.ts" />

import React = require('react');
import ReactPropTypes = React.PropTypes;
import ReactComponent = require('../../utils/react/reactComponent');


interface ExampleProps {
	id: string;
	className: string;
	hasValue?: boolean;
	style?: any;
}

interface ExampleElement {
}

class Example extends ReactComponent<ExampleProps, any> {
	static PropTypes: React.ValidationMap<ExampleProps> = {
		id: ReactPropTypes.string,
		className: ReactPropTypes.string,
		hasValue: ReactPropTypes.bool,
		style: ReactPropTypes.object
	}
	
	static defaultProps: ExampleProps = {
		id: 'uuid-0',
		className: 'blueClass',
		hasValue: false,
		style: {}
	}
	
	public render(): React.DOMElement<ExampleElement> {
		return (
			(React.createElement("div", {id: this.props.id, className: this.props.className}, "Hello World!"))
		)
	}
};

export = Example;
```

Even though defaultProps is explicitly of type ExampleProps, style and hasValue are not really optional in this case because if you don't pass it in when rendering, the compiler still complains. This gets even more weird when you comment out defaultProps and it's still no go.

**Comment by jbrantly** [comment]
OK! After much head banging, I believe I figured out the issue. "Simply" upgrade to TypeScript 1.5 :) I think the type argument matching was failing due to this: Microsoft/TypeScript#1446. I upgraded the project to use TS 1.5 and the issue went away.

Just some notes on upgrading to TS 1.5: See ivogabe/gulp-typescript#91 for changing gulp-typescript and you will need to delete some stuff out of node.d.ts like `WeakMap`, `Set`, etc that I'm guessing TS 1.5 removed from the ES5 target.

**Comment by dho825** [comment]
@jbrantly Holy cow! That's so weird! I was using TS 1.5 globally, but locally it was 1.4...I can't believe that such a "simple" upgrade fixed the issue. I guess I'm reassured that it wasn't my stupidity or newness to both TS and React, and other people had issues with the same general issue.

Man, finding issue #1446 probably took a bit of time. My OCD side thanks you profusely! At the end thanks so much to both of you and @vsiao...I have a better understanding of both TS and React from this!
