### ISSUE TITLE
superagent.d.ts/supertest.d.ts missing SuperAgent.delete()

### ISSUE THREAD

**Issue by tkrotoff** [borisyankov/DefinitelyTyped#4512]
del() should be an alias on delete()
See https://github.com/borisyankov/DefinitelyTyped/blob/master/superagent/superagent.d.ts#L28

It is unclear to me in the original source code if it is superagent that defines delete() or supertest.
See https://github.com/visionmedia/supertest/commit/87412836488a4ccab97abe8b5ac5cd4338aeb5a3
See also https://github.com/visionmedia/superagent/issues/605

**Comment by horiuchi** [comment]
@tkrotoff I fixed it.

**Comment by tkrotoff** [comment]
Cool! tested and works: now `request(app).delete()` is recognized
