### ISSUE TITLE
lodash([1,2,3]).map(i => i).sum() failed

### ISSUE THREAD

**Issue by heycalmdown** [borisyankov/DefinitelyTyped#4532]
```typescript
            _([1,2,3]).map(i => i).value(); // works
            _([1,2,3]).map(i => i).reduce((sum, e) => sum + e, 0); // works
            _([1,2,3]).sum(); // works
            _([1,2,3]).map(i => i).sum(); // doesn't works
```
The last line occurs `Error TS2346: Supplied parameters do not match any signature of call target.`
I don't get why it says about the signature of call target.

**Comment by vvakame** [comment]
@heycalmdown please send a PR.

**Comment by heycalmdown** [comment]
I'm not currently understanding why it occurs the error.

**Comment by chrootsu** [comment]
https://github.com/borisyankov/DefinitelyTyped/pull/5048 I think it's fix the problem.
_.map() returns LoDashArrayWrapper<T> which did not contain the necessary signature _.sum() without arguments.
