### ISSUE TITLE
Definition request: devextreme 15.1

### ISSUE THREAD

**Issue by daveshapiro** [borisyankov/DefinitelyTyped#4549]
DevExtreme has updated to v15.1 and adds some nice new functionality.  Could we please get an updated d.ts for this?

**Comment by Seteh** [comment]
Hello @daveshapiro, 

At the moment, you can get TypeScript definitions for DevExtreme 15.1 from [here](https://github.com/DevExpress/bower-devextreme/blob/master/ts/dx.all.d.ts).

**Comment by daveshapiro** [comment]
Beauty!  Thank you very much, @Seteh!
