### ISSUE TITLE
Allow TS 1.5 definitions

### ISSUE THREAD

**Issue by alexeagle** [borisyankov/DefinitelyTyped#4564]
Angular2 is written in TS 1.5 and so our generated `.d.ts` file is naturally in 1.5 (destructuring parameters for example).
I see there is a 1.5 branch on DT - what is the plan for allowing definitions to use 1.5 language syntax? Can you just update your build+test to use TS 1.5 beta? IIUC existing typings should not be broken by that upgrade.

I have a doc with all our issues generating our typings file: https://docs.google.com/document/d/1nNebWTiLzz5ePcit_bjZPtaiSIFU4EsQKUlX7LX0c0A/edit

**Comment by rossross** [comment]
+1 can't add my definitions because they are all the 1.5 syntax.

**Comment by alexeagle** [comment]
I found it quite easy to downgrade them to 1.4 (mostly introduce an
interface for destructured args)

**Comment by rossross** [comment]
Unfortunately when you're dealing with 2000 lines of definition files that's not really a feasible option.

**Comment by alexeagle** [comment]
We may write a transformer as part of the angular build, if this issue
stays unresolved.

**Comment by nycdotnet** [comment]
In general, DefinitelyTyped accepts definitions using features in the latest officially (non-beta) released version of TypeScript.  I have a feeling 1.5 should be officially released in the next week or two, so this should become moot presently.  https://github.com/Microsoft/TypeScript/milestones

**Comment by alexeagle** [comment]
1.5 is GA
What needs to be done?

**Comment by vvakame** [comment]
oh, sorry. DT is already use 1.5.3! https://github.com/borisyankov/DefinitelyTyped/blob/master/package.json#L39
