### ISSUE TITLE
d3.event.pageX

### ISSUE THREAD

**Issue by HelloBugs** [borisyankov/DefinitelyTyped#4590]
Hi, 
I'm building an interactive graph using D3 and typescript. But I have trouble to get typescript support for: <code>d3.event.pageX</code> and <code>d3.event.pageY</code>.  

Property 'pageX' does not exist on type 'Event'
Property 'pageX' does not exist on type 'Event'

I'm new to the typescript world. So I'm not sure this is something missing in the definition or simply because I used it wrong. 

Thanks

**Comment by vvakame** [comment]
@HelloBugs please send a pull reuqest. I'll review it.

**Comment by Geoff-Ford** [comment]
Was anything else done to resolve this? It is still an issue as I get the same transpile errors as above.

**Comment by gebeng** [comment]
solved this by using <any>d3.event
for detail:  https://stackoverflow.com/questions/38019090/cant-transpile-typescript-due-to-d3-event-error
