### ISSUE TITLE
require.d.ts does not declare `module` "magic" module

### ISSUE THREAD

**Issue by kfranqueiro** [borisyankov/DefinitelyTyped#4620]
The [`module` magic module](https://github.com/jrburke/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define#module) can't be imported without additional typings.

I was able to get it to work with the following:

```ts
declare module 'module' {
	var mod: {
		config: () => any;
		id: string;
		uri: string;
	}
	export = mod;
}
```

(`config` is for [`module.config`](http://requirejs.org/docs/api.html#config-moduleconfig), though that isn't mentioned in the aforementioned wiki page.)

Is there a reason this was omitted, or is it an oversight?

**Comment by vvakame** [comment]
@kfranqueiro please send a pull request. I'll review it.
