### ISSUE TITLE
mocha.d.ts should not depend on node.d.ts

### ISSUE THREAD

**Issue by ashwinr** [borisyankov/DefinitelyTyped#4701]
Mocha works on both browsers and node -- it *should* not be bringing in node definition files for those of us that use it only on the browser. This is causing us problems when we try to update it.

**Comment by sixinli** [comment]
seems like it's introduced here: https://github.com/borisyankov/DefinitelyTyped/pull/4548

**Comment by thasner** [comment]
:+1:
