### ISSUE TITLE
when.d.ts should have non-promise reason callback for catch with Error

### ISSUE THREAD

**Issue by drinchev** [borisyankov/DefinitelyTyped#4711]
Hey there,

IMHO The following [line](https://github.com/borisyankov/DefinitelyTyped/blob/6387999eb899d0ba02d37dd8697647718caca230/when/when.d.ts#L151) :

    catch<U>(exceptionType: any, onRejected?: (reason: any) => Promise<U>): Promise<U>;

is wrong, it should be more permissive :

    catch<U>(exceptionType: any, onRejected?: (reason: any) => U | Promise<U>): Promise<U>;

It should be the same way the other catchers are declared in the overload :

    catch<U>(onRejected?: (reason: any) => U | Promise<U>): Promise<U>;
    catch<U>(filter: (reason: any) => boolean, onRejected?: (reason: any) => U | Promise<U>): Promise<U>;

**Comment by vvakame** [comment]
@drinchev please send a pull request. I'll review it.
