### ISSUE TITLE
Node's `require` should implement a new interface `NodeRequire` (rather than direct signature) for specialized extension by other libraries

### ISSUE THREAD

**Issue by Gitgiddy** [borisyankov/DefinitelyTyped#4740]
This is motivated by trying to use Electron (Atom shell) with Typescript.  I don't know anything about Node.js, but at least this Electron package which uses Node takes advantage of the `require()` function object defined by Node.  I believe that we cannot use the Typescript `import` statement because Electron is not compatible with AMD/RequireJS and TypeScript doesn't know what to do with `import` statements without enabling AMD module support.

Using the [quick start](https://github.com/atom/electron/blob/master/docs/tutorial/quick-start.md) as is, even with the GitHub-Electron.d.ts stuff loaded in, statements like `var BrowserWindow = require('browser-window')` make the `BrowserWindow` class show up to be of type `any` (which is not very helpful) and all my other attempts to get it working otherwise have failed.  So here's my solution but it needs a subtle change to how `require()` is defined.

node.d.ts currently defines its require as:

    declare var require: {
        (id: string): any;
        resolve(id: string): string;
        cache: any;
        extensions: any;
        main: any;
    }

but this is obnoxious because this means that the require signature cannot be specialized by string name.

If require were defined like this instead:

    interface NodeRequire {
        (id: string): any;
        resolve(id: string): string;
        cache: any;
        extensions: any;
        main: any;
    }
    
    declare var require: NodeRequire;

... then for a specific library we could extend it like so:

    interface NodeRequire {
        (id: 'browser-window'): { new (options?: GitHubElectron.BrowserWindowOptions) : GitHubElectron.BrowserWindow }
        (id: 'crash-reporter'): { start(options?: CrashReporterStartOptions): void; getLastCrashReport(): CrashReporterPayload; }
    }

and get proper intellisense for

    require('crash-reporter').start();

and 

    mainWindow = new BrowserWindow({ width: 800, height: 600 });

This is necessary because I believe that a `declare`d `var` cannot be extended directly, but an interface that it implements *can* be.  I believe that the resulting require type information would be exactly the same as the current implementation.

My `crash-reporter` example required some tweaking to the GitHub-Electron.d.ts packages, but I'll tackle that next (the module has a string name which I cannot refer to so I had to pull out the embedded interface for CrashReporterPayload and repeat the module definition inline).  There's no point in those definitions being more correct if we don't get the type inferencing with THIS suggestion anyway.

Perhaps I'm missing something big, so I'd love to be corrected on that!  But I don't see examples of how to use the GitHub-Electron.d.ts in a full and effective setup.

There are other places that the `require` functionality is repeated (`module.require()`) and I'm not familiar with the node.js api to know where to make this change everywhere or if that would be the right thing to do.

**Comment by nycdotnet** [comment]
PR Merged.  Thanks!
