### ISSUE TITLE
mongoose.Types.ObjectId ctor doesn't not require id

### ISSUE THREAD

**Issue by lazutkin** [borisyankov/DefinitelyTyped#4742]
to=@horiuchi 

Ctor definition of `mongoose.Types.ObjectId` doesn't require an `id` arg to be provided and [must be changed to be optional](https://github.com/borisyankov/DefinitelyTyped/blob/master/mongoose/mongoose.d.ts#L82).

**Comment by horiuchi** [comment]
@lazutkin Thank you for suggestion the bug.
It's a correct: https://github.com/mongodb/js-bson/blob/master/lib/bson/objectid.js#L41
Please send the pull request, and I'll review it :smile:

**Comment by lazutkin** [comment]
OK, here is my PR
