### ISSUE TITLE
Model constructor (new) - parameter should be optional.

### ISSUE THREAD

**Issue by garyham** [borisyankov/DefinitelyTyped#4765]
Model constructor takes an optional document so...

This (line 138 - 7776946d2f34daffaf37ff4ecac032666aeb566e)

        export interface Model<T extends Document> extends NodeJS.EventEmitter {
             new(doc: Object): T;

Should read

        export interface Model<T extends Document> extends NodeJS.EventEmitter {
             new(doc?: Object): T;

**Comment by horiuchi** [comment]
@garyham Sure.
Please send pull request, so I'll review it.

**Comment by garyham** [comment]
Done...PR #4790

**Comment by horiuchi** [comment]
@garyham Thank you for your contribution!
