### ISSUE TITLE
angular2/forms: Validators.required is missing

### ISSUE THREAD

**Issue by Ludo09** [borisyankov/DefinitelyTyped#4769]
Hi everyone,
```typescript Validators.required``` seems to be missing from ```angular2.d.ts```.

Also something I don't understand is why I have to import Validator from ```angular2/angular2``` and not ```angular2/forms```?

**Comment by alexeagle** [comment]
We have an internal package structure which is `angular2/[component]`, and it's possible to access some angular internals by importing from there. The public API surface is all re-exported into the `angular2/angular2` namespace.

Thanks for reporting the issue, I opened https://github.com/angular/angular/issues/3175 to track.
