### ISSUE TITLE
(question): IndexedDB?

### ISSUE THREAD

**Issue by ttowncompiled** [borisyankov/DefinitelyTyped#4786]
Is there no definitions file for IndexedDB according to the API provided by MDN?

**Comment by TeamworkGuy2** [comment]
The latest version of [lib.d.ts](https://github.com/Microsoft/TypeScript/blob/master/bin/lib.d.ts) already contains indexedDB definitions.  Visual Studio 2015 RC contains these definitions if you install TypeScript language services.

**Comment by ttowncompiled** [comment]
Thank you.

**Comment by 1w3j** [comment]
@TeamworkGuy2  lib.d.ts is no longer available, still need definitions for IndexedDB

**Comment by TeamworkGuy2** [comment]
Looks like microsoft refactored the TypeScript definitions. Try [lib.dom.d.ts](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts)
