### ISSUE TITLE
Angular-Material MDDialog service needs updated

### ISSUE THREAD

**Issue by robertbaker** [borisyankov/DefinitelyTyped#4843]
Working on fixing it, this is what I have so far. @mtraynham

I also propose to change the interface names to match angular's style of prefixing interfaces with I.

```
interface MDPresetDialog<T> {
        title(title: string): T;
        content(content: string): T;
        ok(ok: string): T;
        theme(theme: string): T;
        templateUrl(templateUrl?: string);
        template(template?: string);
        targetEvent(targetEvent?: MouseEvent);
        scope(scope?: angular.IScope); // default: new child scope
        preserveScope(preserveScope?: boolean); // default: false
        disableParentScroll(disableParentScroll?: boolean); // default: true
        hasBackdrop(hasBackdrop?: boolean); // default: true
        clickOutsideToClose(clickOutsideToClose?: boolean); // default: false
        escapeToClose(escapeToClose?: boolean); // default: true
        focusOnOpen(focusOnOpen?: boolean); // default: true
        controller(controller?: string|Function);
        locals(locals?: {[index: string]: any});
        bindToController(bindToController?: boolean); // default: false
        resolve(resolve?: {[index: string]: angular.IPromise<any>})
        controllerAs(controllerAs?: string);
        parent(parent?: string|Element|JQuery); // default: root node
        onComplete(onComplete?: Function);
        ariaLabel(ariaLabel: string);
    }
```

**Comment by mtraynham** [comment]
@robertbaker I'm fine with prefixing the interfaces with `I`.  I didn't see these methods in the docs, so I just want to be sure that it's all supported.  Also, if we are going to do this, there are a few other changes I wouldn't mind seeing as well.  I was going to do it, but I noticed you already had a PR, so I'll just list them:
- Copy current `angular-material.d.ts` to `angular-material-0.9.0.d.ts` (prior to any change)
- Change the comments at the top to say 0.10.0
- Update IMDIconProvider:
```
    interface IMDIconProvider {
        icon(id: string, url: string, viewBoxSize?: number): IMDIconProvider; // viewBoxSize default: 24
        iconSet(id: string, url: string, viewBoxSize?: number): IMDIconProvider; // viewBoxSize default: 24
        defaultIconSet(url: string, viewBoxSize?: number): IMDIconProvider; // viewBoxSize default: 24
        defaultViewBoxSize(viewBoxSize: number): IMDIconProvider; // default: 24
        defaultFontSet(name: string): IMDIconProvider;
    }
```
- Also add the chainging to IMDToastPreset?

Out of scope, anything changed with the MDTheming stuff?

**Comment by robertbaker** [comment]
@mtraynham Check the dialog demo source code, it's documented.

I don't know if anything changed, I have theme code and it still works.

Since the typings are namespaced, you could remove the MD prefix too.

**Comment by mtraynham** [comment]
@robertbaker by documentation, I meant in the Methods specification section:
https://material.angularjs.org/latest/#/api/material.components.dialog/service/$mdDialog

Feel free to keep making changes as you see fit :smile:

**Comment by mtraynham** [comment]
Can we change the title of your open PR and add the changes there?  https://github.com/borisyankov/DefinitelyTyped/pull/4845

**Comment by robertbaker** [comment]
@mtraynham done.

**Comment by mtraynham** [comment]
@robertbaker awesome, thanks man!

**Comment by xiphiaz** [comment]
@robertbaker I think the `.parent()` method of `IToastPreset` is missing? It doesn't actually appear to be documented in the material docs, however it works (`"angular-material": "~0.10.0",` in bower).

Example
```ts
this.$mdToast.show(
    $mdToast.simple()
        .hideDelay(2000)
        .position('top')
        .content(err.message)
        .parent('#loginDialog')
);
```

**Comment by mtraynham** [comment]
@vvakame Can close this, #4845 was merged

**Comment by robertbaker** [comment]
@xiphiaz Sorry didn't see that until now. Will do a PR for it.
