### ISSUE TITLE
lodash _.contains() should search object values, not keys

### ISSUE THREAD

**Issue by dbeckwith** [borisyankov/DefinitelyTyped#4854]
According to the [docs](https://lodash.com/docs#includes), `contains` should search values of an object, not [keys](https://github.com/borisyankov/DefinitelyTyped/blob/master/lodash/lodash.d.ts#L2205). The test for this is written correctly for the proper behavior, but coincidentally allows the incorrect behavior by providing a key that's a string. Also it should have the `includes` alias, currently it only has `contains` and `include` (actually, `contains` and `include` should be aliases for `includes`). I can submit a PR later today to fix, as well as a better test.

**Comment by vvakame** [comment]
@dbeckwith please send a pull request. I'll review it.
