### ISSUE TITLE
JQuery $.when is typed incorrectly

### ISSUE THREAD

**Issue by JohnGalt1717** [borisyankov/DefinitelyTyped#4888]
It's using generics to define the done values that come back. The problem is that it's assuming all promises passed into it will be of the same type which is not valid. The types can all be different.

**Comment by vvakame** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
Hi @JohnGalt1717,

In which case presumably you can type assert with `any` or similar to cater for those edge cases?  If you've a better proposal for how to type this then feel free to submit a PR and we can go from there.

Closing for now.

**Comment by JohnGalt1717** [comment]
Either put it back the way it was where the result types were <any> so that it works properly and doesn't require a hack, or make every return type a different Type based on the parameters passed into the function. (don't know if this is possible)

But the way it is right now would not work for 99% of the uses of $.when so you're requiring it to be hacked essentially all of the time.

**Comment by johnnyreilly** [comment]
Hi @JohnGalt1717,

You may well be right - I don't use the promises in jQuery myself as they are ["broken" / not Promises/A+ compliant](https://blog.domenic.me/youre-missing-the-point-of-promises/).  

You suggest that a problem that has been introduced into the typing recently.  That being the case please feel free to submit a PR with your alternative implementation (the previous implementation?) and we'll look at it and discuss.

Thanks.

**Comment by JohnGalt1717** [comment]
What's a PR? I've submitted this bug already. Just put it back the way it was because your change isn't a valid assumption.

**Comment by johnnyreilly** [comment]
PR = Pull Request.  I don't know exactly what the change you are referring to is - but you can help me there.  If you submit a PR with the correct typing as you see it.  

Given what you've said about it being correct in the past you should be able to go through the jquery.d.ts's history and find what you are looking for which will make creating the PR pretty straightforward.
