### ISSUE TITLE
Is there a way to use WinJs / WinRT?

### ISSUE THREAD

**Issue by inf3rno** [borisyankov/DefinitelyTyped#4950]
As far as I understand it is available in this fork: https://github.com/anprak/DefinitelyTyped Is it not complete, or why wasn't it merged yet?

**Comment by vvakame** [comment]
um? please ask to that repository.

**Comment by inf3rno** [comment]
@vvakame 
![nevtelen](https://cloud.githubusercontent.com/assets/408911/8761444/3ff94ff2-2d52-11e5-93a1-34505abf728e.png)

So where should I ask?
