### ISSUE TITLE
React intrinsic props

### ISSUE THREAD

**Issue by tinganho** [borisyankov/DefinitelyTyped#4963]
React have some props already filled like `this.props.children`. Don't you think it should be augmented with that?

```typescript
    interface ReactIntrinsicProps {
        key?: string | number;
        children?: string | number | Element | Element[];
    }

    // Base component for plain JS classes
    class Component<P, S> implements ComponentLifecycle<P, S> {
        constructor(props?: P, context?: any);
        setState(f: (prevState: S, props: P) => S, callback?: () => any): void;
        setState(state: S, callback?: () => any): void;
        forceUpdate(): void;
        props: P & ReactIntrinsicProps;
        state: S;
        context: any;
        refs: {
            [key: string]: Component<any, any>
        };
    }
```

**Comment by vvakame** [comment]
@pspeter3 @vsiao how about it?

**Comment by pspeter3** [comment]
I think you're saying that key and children should be added to ReactProps. I believe that is only true if you use JSX

**Comment by tinganho** [comment]
I don't think it is somethingJSX specific?

**Comment by jbrantly** [comment]
These aren't JSX specific, and something like this does make sense to me. However...

1) Intersection types aren't available until TS 1.6, so we'd be a while out before we could add.
2) I'm not sure "key" is passed down in the props, and I'm too lazy to actually check. I know it's treated separately on the result of React.createElement.

Other than that, +1

**Comment by vsiao** [comment]
There's https://github.com/borisyankov/DefinitelyTyped/blob/master/react/react.d.ts#L330-334, btw, which we use at Asana like so:

```ts
interface Props extends React.Props<Button> {
    onClick: ...
}

class Button extends React.Component<Props, {}> {
}
```

This also provides the right types for callback refs. For example, in

```ts
React.createElement(Button, {
    ref: button => this._button = button
})
```

the type of `button` is inferred to be `Button`. There's a downside to this approach though, which @jbrantly already mentioned. The `key` property is not preserved on the `props` object after element creation, so the types aren't quite perfect. But it's the best that we can do for now, I think.

**Comment by tinganho** [comment]
@vsiao ok thanks. That seems like a good approach. Closing for now.
