### ISSUE TITLE
error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher.

### ISSUE THREAD

**Issue by fmsouza** [borisyankov/DefinitelyTyped#4965]
I'm using TypeScript downloaded direct from Microsoft/TypeScript, I think the version is "1.5.3".

When I'm trying to compile my code in io.js with compile to ES6 flag, it raises this error lots of times.

```error TS1202: Import assignment cannot be used when targeting ECMAScript 6 or higher. Consider using 'import * as ns from "mod"', 'import {a} from "mod"' or 'import d from "mod"' instead.```

**Comment by vvakame** [comment]
sorry, This repository is supporting for 1.4.1 only. 1.5.3 is not released yet at npm.

**Comment by enlight** [comment]
1.5.3 is now supported so @vvakame (or someone else) can close this issue :)
