### ISSUE TITLE
Backbone defs should reference jQuery, not JQuery

### ISSUE THREAD

**Issue by danielgindi** [borisyankov/DefinitelyTyped#5000]
As you probably import the jQuery refs in an IDE, and then the Backbone refs, but Backbone can't find JQuery...
It's just a simple find & replace

**Comment by vvakame** [comment]
@danielgauci please send a pull request. I'll review it.

**Comment by danielgindi** [comment]
Well now that I dive more into the `jquery.d.ts` I'm not sure that we need to change it, as the interface itself is `JQuery`, and the var is `jQuery`.
I think maybe Webstorm just doesn't interpret that correctly.
