### ISSUE TITLE
TypeScriptCompile on Visual Studio 2015

### ISSUE THREAD

**Issue by dirkrombauts** [borisyankov/DefinitelyTyped#5074]
Hi,

I just upgraded the nuget packages of knockout.d.ts and jquery.d.ts in a solution in VS2015 that used to compile. Now the solution does not compile anymore, with lots of errors in those two d.ts files. If I set their build action to None, the error goes away (obviously). Judging from some other issues on this site, the build action of "TypeScriptCompile" is intentional ... so is there anything obvious I'm doing wrong? What information should I provide you so you can better understand?

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by staxmanade** [comment]
Off hand, I don't have any ides.

Do any of the details in these links provide any clues?

http://stackoverflow.com/questions/30091947/typescript-compile-options-on-visual-studio-2015-rc
https://support.microsoft.com/en-us/kb/3025133
https://github.com/Microsoft/TypeScript/issues/2294

Hope this helps

**Comment by dirkrombauts** [comment]
I found the solution: I needed to edit the project file and set the TypeScriptToolsVersion to 1.4 as described in http://stackoverflow.com/questions/18293590/typescript-error-ts1005-expected
