### ISSUE TITLE
request-promise incorrect return type on options.transform

### ISSUE THREAD

**Issue by jamesrmccallum** [borisyankov/DefinitelyTyped#5078]
export interface Options extends request.Options {
            simple?: boolean;
            transform?: (body: any, response: http.IncomingMessage) => number; 
            resolveWithFullResponse?: boolean;
        }

See above code, the method interface for 'transform?' returns a number, this can only be an any i think.

    export interface Options extends request.Options {
            simple?: boolean;
            transform?: (body: any, response: http.IncomingMessage) => any; 
            resolveWithFullResponse?: boolean;
        }

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by AyaMorisawa** [comment]
Fixed in #5456 .
