### ISSUE TITLE
fbsdk issue: FBLoginOptions has "scopes" (and it should be "scope")

### ISSUE THREAD

**Issue by yoav-zibin** [borisyankov/DefinitelyTyped#5092]
interface FBLoginOptions{
auth_type ?: string;
scopes ?: string; // WRONG: should be "scope"
return_scopes ?: boolean;
enable_profile_selector ?: boolean;
profile_selector_ids ?: string;
}

See:
https://developers.facebook.com/docs/reference/javascript/FB.login/v2.4

scope
string
Comma separated list of extended permissions
return_scopes
boolean

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by yoav-zibin** [comment]
I think I managed to create one :)
https://github.com/borisyankov/DefinitelyTyped/pull/5107
