### ISSUE TITLE
node.d.ts: readline.ReadLine.setPrompt takes only one argument

### ISSUE THREAD

**Issue by yourpalal** [borisyankov/DefinitelyTyped#5224]
Current versions of `setPrompt()` take only a single string argument. The [current mapping](https://github.com/borisyankov/DefinitelyTyped/blob/master/node/node.d.ts#L784) takes an additional `length: number` argument.

[implementation](https://github.com/nodejs/node/blob/master/lib/readline.js#L164)
[current docs](https://nodejs.org/api/readline.html#readline_rl_setprompt_prompt)

It looks like this change first appeared in [0.11.0](https://nodejs.org/docs/v0.11.0/api/readline.html).

**Comment by vvakame** [comment]
@yourpalal please send pull request. I'll review it.

**Comment by yourpalal** [comment]
Sorry about the doubled commits. I didn't realise I had forked this repo about 1200 commits ago, so my changes were quite far away from the current HEAD.
