### ISSUE TITLE
BingMaps events on entities

### ISSUE THREAD

**Issue by doubret** [borisyankov/DefinitelyTyped#5235]
Hello, thanks for the bing maps typings.

I have a small question though.
How am i supposed to use the events declared on entities like Pushpin or Infobox ?
I tried setting them to my own functions but they never get called, to get my functions called i need to register them using the Events class.

Am i missing something here ? Are the events declared on entities usable to register custom handlers automatically ?

Thanks.

**Comment by vvakame** [comment]
@ericrtodd ?

**Comment by ericrtodd** [comment]
Hi @doubret,

var pushpin = ....;
Microsoft.Maps.Events.addHandler(pushpin,"click",()=>alert("hi"));

There is a pretty good SDK demo at: 
https://www.bingmapsportal.com/isdk/ajaxv7#Pushpins9

-Eric

**Comment by doubret** [comment]
Hi @ericrtodd,
I use the Events class this way, but as i saw the events properties on the Pushpin class i wondered if there was another way to register my callbacks. 

I suppose these event properties are there for documentation purpose but it is somewhat confusing as they have no real existence in the class. 
Shouldnt they be removed to avoid the confusion ?

Thanks

**Comment by ericrtodd** [comment]
Hi @doubret,

You're absolutely right. I'll probably make a push tonight.

-Eric

**Comment by doubret** [comment]
Perfect.
If you can include the changes from this issue too it would be great : https://github.com/borisyankov/DefinitelyTyped/issues/5243

Thank you.

**Comment by doubret** [comment]
Thank you.
