### ISSUE TITLE
expect.js.d.ts intellisense does not work

### ISSUE THREAD

**Issue by speedy32** [borisyankov/DefinitelyTyped#5239]
I try to use intellisense on expect.js.d.ts in my project but it seems to not work as expected.

File expectTest.js:
<pre>
/// &lt;reference path="../typings/tsd.d.ts"/&gt;
var	expect = require('expect.js')
expect(''). 
</pre>
and here I'm not getting any suggestions 

at tsd.d.ts of course I have reference:
<pre>
/// &lt;reference path="expect.js/expect.js.d.ts" /&gt;
</pre>

**Comment by vvakame** [comment]
you should use `import expect = require('expect.js')`. `var foobar = require("foobar");`.
http://www.typescriptlang.org/Handbook#modules-going-external
