### ISSUE TITLE
Microsoft.Maps.Directions.d.ts implicit any types

### ISSUE THREAD

**Issue by doubret** [borisyankov/DefinitelyTyped#5243]
In Microsoft.Maps.Directions.d.ts definition file, in the Waypoint class, these three declarations break the disable implicit 'any' types rule :

		/**
		*	Occurs when the any properties of the waypoint change or are updated.
		**/
		changed(waypointEventArgs: WaypointEventArgs);

		/**
		*	Occurs when a geocoding request for the waypoint’s address is made.
		**/
		geocoded(waypointEventArgs: WaypointEventArgs);

		/**
		*	Occurs when a reverse geocoding request for the waypoint’s location is made. This happens when no address is provided for the waypoint, or if the waypoint is dragged (in which case its location is changed).
		**/
		reverseGeocoded(waypointEventArgs: WaypointEventArgs);

I guess we can just add ": any" at the end of the declaration to make them explicit and then comply to the rule.

**Comment by vvakame** [comment]
@bmiller1 ?

**Comment by bmiller1** [comment]
From the current version of Microsoft.Maps.Directions.d.ts:

        changed: (args: WaypointEventArgs) => void;
        geocoded: (args: WaypointEventArgs) => void;
        reverseGeocoded: (args: WaypointEventArgs) => void;

Those functions already have return types and they do pass the implicit any rule.  Adding the comments would be good though.

**Comment by doubret** [comment]
Completely sorry, i didn't realize i was using definition files not coming from DefinitelyTyped.
I deleted the other files and switched to the DefinitelyTyped nuget package.

The previous problem is fixed but i have other ones :

- the LocationRect class definition is wrong, it defines the getSoutEast methos instead of getSoutheast (the 2nd 'e' should not be a capital letter).
```javascript
        getSoutheast(): Location;
```
- The EntityCollection constructor should declare the option argument optional.
```javascript
        constructor(options?: EntityCollectionOptions);
```
- Properties in the EntityCollectionOptions should be optional.
```javascript
    export interface EntityCollectionOptions {
        bubble?: boolean;
        visible?: boolean;
        zIndex?: number;
    }
```
- In Map class, tryLocationToPixel and tryPixelToLocation only support array arguments, they should support array or single argument types.
```javascript
        tryLocationToPixel(locations: Array<Location>|Location, reference?: PixelReference): any;
        tryPixelToLocation(points: Array<Point>|Point, reference?: PixelReference): any;
```

**Comment by bmiller1** [comment]
I agree with doubret's suggested changes

**Comment by vvakame** [comment]
thanks! please send a pull request.

**Comment by doubret** [comment]
bmiller1 or I ?

**Comment by bmiller1** [comment]
You.

**Comment by doubret** [comment]
Ok, no problems. 
I'll do that in the weekend.

**Comment by doubret** [comment]
All has already been fixed by @ericrtodd.
The issue can be closed.
