### ISSUE TITLE
angular2 - angular2-2.0.0-alpha.34.d.ts definition file filled with "?:"

### ISSUE THREAD

**Issue by pbc** [borisyankov/DefinitelyTyped#5335]
I have noticed that angular2-2.0.0-alpha.34.d.ts  and angular2.d.ts files , located here : 

https://github.com/borisyankov/DefinitelyTyped/blob/master/angular2/angular2-2.0.0-alpha.34.d.ts
https://github.com/borisyankov/DefinitelyTyped/blob/master/angular2/angular2.d.ts

are filled with "?:" instead of ":" in field and param declarations for some reason which makes these files unusable.

For e.g.:

    View(obj: {
      templateUrl?: string,
      template?: string,
      directives?: List<Type | any | List<any>>,
      renderer?: string,
      styles?: List<string>,
      styleUrls?: List<string>,
    }): ViewDecorator;

should be:

    View(obj: {
      templateUrl: string,
      template: string,
      directives: List<Type | any | List<any>>,
      renderer: string,
      styles: List<string>,
      styleUrls: List<string>,
    }): ViewDecorator;

Quick search and replace in an editor fixes the problem but these files are no longer usable in any automated deployment.

**Comment by ericmartinezr** [comment]
What do you mean by 'unusable'?

See this
http://www.typescriptlang.org/Handbook#functions-optional-and-default-parameters

**Comment by pbc** [comment]
I mean that the definition file is not going to compile with tsc 1.5.3, but I wasn't aware that this is how you define optional params (still learning)

I will restore the file to the previous version on my machine and will investigate.

**Comment by pbc** [comment]
I see what it was now. My rails application was using incorrect compiler.

This ticket is invalid then.

Thank you.
