### ISSUE TITLE
Type definitions for Vortex Web client vortex-web-client.d.ts

### ISSUE THREAD

**Issue by WalterRawley** [borisyankov/DefinitelyTyped#5499]
I've been only using JavaScript and TypeScript for a couple of months so maybe I'm wrong but I don't understand with the delivered definition how to specify custom QoS.
In JavaScript it's possible to write:
var dwQos = new dds.DataWriterQos(dds.Partition("chatroom"), dds.Reliability.Reliable, dds.Durability.Persistent);

Qos are sent to server using pairs. So for exemple dds.Reliability.Reliable maps to {"id":5,"k":3}.
With the type definition, I cannot get the same or only deserialization errors.

Thanks.

**Comment by vvakame** [comment]
@Pro ?

**Comment by Pro** [comment]
Does it work if you leave out the `Partition` Qos?
I.e. `var dwQos = new dds.DataWriterQos(dds.Reliability.Reliable, dds.Durability.Persistent);`
I'm currently only using emtpy Qos, but will test it tomorrow.
Can you post a minimal code example (http://stackoverflow.com/help/mcve) which I can check?

**Comment by Pro** [comment]
@WalterRawley You can use the rest case for a simple example where you can try to reproduce the problem: https://github.com/borisyankov/DefinitelyTyped/blob/2d4c4679bc2b509f27435a4f9da5e2de11258571/vortex-web-client/vortex-web-client-tests.ts

**Comment by WalterRawley** [comment]
@Pro It doesn't compile (with VS2013). I even didn't catch we should use that way. So to make it compile, I added a "static" instruction for each QoS policy in your definition file:

export class Durability implements Policy {
   static Volatile:any;
   static TransientLocal:any;
[...]

I'll try this way another day because for now I have another problem running the sample. I don't understand why, but it's not related to this issue.

**Comment by Pro** [comment]
Should now be fixed: https://github.com/borisyankov/DefinitelyTyped/commit/5037a214342644ce5425c74d41fd1721b2a07a08

Issue can be closed.

**Comment by WalterRawley** [comment]
Works fine. 
Thanks a lot!
