### ISSUE TITLE
Can no longer use Long.js definition.

### ISSUE THREAD

**Issue by eugenega** [borisyankov/DefinitelyTyped#5527]
Long.js definition https://github.com/borisyankov/DefinitelyTyped/blob/master/long/long.d.ts now starts with: declare module "long". 
I used to write:
var x: dcodeIO.Long;

Right now it is broken and I cannot use Long anymore.

What is the way now to define a variable in TS of a Long type?

**Comment by TeamworkGuy2** [comment]
looks like the new definition allows you can directly access a global type called 'long', for example:
```
/// <reference path=".../long.d.ts" />

import long = require("long"); // from node_modules or equivalent

...

var num: long;
num.equals(12);
```

Hopefully that helps!

**Comment by eugenega** [comment]
I do not use RequireJS or CommonJS thus I cannot use require("long"). I build ts files to js and reference them directly from HTML.
Adding reference and using var num: long;  also does not help.

**Comment by TeamworkGuy2** [comment]
That was just fluff setup example code, sounds like you know what your doing with definition files and ts to js compilation. 
The point was the last 2 lines, the new long.d.ts file defines a module named "long" and allows you to now write:

In your original post, the line:
```
var x: dcodeIO.Long;
```
Can now be written as:
```
var x: long;
```

P.S. If that doesn't work, try this:
```
var x: long.Long;
```

**Comment by eugenega** [comment]
Neither var x: long; nor var x: long.Long; work. TS says "Cannot find symbol..."

**Comment by eugenega** [comment]
The current Long.d.ts support only "require" for RequireJS or CommonJS, e.g. var long = require("long");. New definition no longer supports plain web browser. In the previous long.d.ts version there were lines that support browser
// for browser
declare module dcodeIO {
    export var Long:LongStatic;
}
Now they are deleted. Can we return it?

**Comment by eugenega** [comment]
Closing this question and opening a new issue that I want to be marked as a defect since the last change brakes browser support (see last comment)
