### ISSUE TITLE
.gitignore not ignoring JavaScript test files.

### ISSUE THREAD

**Issue by sourcebits-robertbiggs** [borisyankov/DefinitelyTyped#5547]
Previously the JavaScript output from running a test were ignored. Now the .gitignore file has:
```
!*.js/
```
So, after running test on the run repository, all the JavaScript tests were generated and git flags them all as 271 changes to the repository. Is this how you want this to work, or should these JavaScript files be ignored?

**Comment by horiuchi** [comment]
I add the line to `.gitignore` because of excluding ignored folder, such as `expect.js/`, `oauth.js`, or others folder.
But I think it is not included the JavaScript files in this setting?
What do you use `git`'s version?

**Comment by chocolatechipui** [comment]
The problem is, I we run ```npm test``` in the root directory like we're supposed to before submiting a pull request, that generates js from all the tests in all the directories. That was alright because before these were ignored. Now they're all showing up as additions.

**Comment by horiuchi** [comment]
I done the `npm test`. But generated JavaScript files don't appear git changing file list in my local env.
Please check the `git` version.

My result:
```
$ git --version
git version 2.5.0
```

**Comment by chocolatechipui** [comment]
I'm on git version 2.5.0 as well, but when I run either npm test on the root directory, or tsc on my folder, the resulting test results show up in git as added files.

**Comment by chocolatechipui** [comment]
OK, so I rebooted my laptop. Now they are being ignored :-)

**Comment by horiuchi** [comment]
OK :+1:
