### ISSUE TITLE
angular compile function does not have to return a value

### ISSUE THREAD

**Issue by david-gang** [borisyankov/DefinitelyTyped#5560]
Hi all,
This is a discussion regarding the angular.tsd
This is a cross post from http://stackoverflow.com/questions/32230969/why-do-i-get-error-ts2345-on-directive-definition

In https://docs.angularjs.org/api/ng/service/$compile it is written that "A compile function can have a return value which can be either a function or an object.". It does not say that it has to

For the following code I get an error:

```typescript
 'use strict';
    angular.module('x')
    .directive('tabsPane', TabsPane)

    function TabsPane(itemTabs) {

        return {
            restrict: 'E',
            compile: compileTabs
        };

        function compileTabs(tElement) {
            var template = createTabsTemplate(); //function which i don't include here for brevity
            tElement.append(template);
        }}
```

> error TS2345: Argument of type '(itemTabs: any) => { restrict: string; compile: (tElement: any) => void; }' is not assignable to parameter of type 'any[]'. Property 'push' is missing in type '(itemTabs: any) => { restrict: string; compile: (tElement: any) => void; }'.

I traced the issue down and it is because of:

```typescript
 interface IDirective {
        compile?: IDirectiveCompileFn;
        controller?: any;
        controllerAs?: string;
        bindToController?: boolean|Object;
        link?: IDirectiveLinkFn | IDirectivePrePost;
        name?: string;
        priority?: number;
        replace?: boolean;
        require?: any;
        restrict?: string;
        scope?: any;
        template?: any;
        templateUrl?: any;
        terminal?: boolean;
        transclude?: any;
    }
```

When i change the line:

> compile?: IDirectiveCompileFn;

to 

> compile?: any;

I don't get the error anymore:

For some reason 

> compile?: IDirectiveCompileFn | void;

does not work.

So it looks it is a defect. What is your view?

**Comment by vvakame** [comment]
What with this?
```
        function compileTabs(tElement) {
            var template = createTabsTemplate(); //function which i don't include here for brevity
            tElement.append(template);
            return null;
        }}
```

**Comment by david-gang** [comment]
This would solve the problem
