### ISSUE TITLE
Definitions for Polymer

### ISSUE THREAD

**Issue by 00001** [borisyankov/DefinitelyTyped#561]
I realise this is asking for a lot, but definition files for the Polymer project would be great!

http://www.polymer-project.org

**Comment by lgrignon** [comment]
Sorry I didn't see that earlier but I started to create some definitions since I needed it:
https://github.com/lgrignon/DefinitelyTyped/tree/master/polymer

Some have already been pulled, and some others are waiting for inclusion.

**Comment by davej** [comment]
@lgrignon: Why are certain properties required by the PolymerElement interface? e.g. `resizableAttachedHandler()`, `resizableDetachedHandler()`, etc..

**Comment by lgrignon** [comment]
Hello Davej,
Polymer provides those methods when you pass your component to the Polymer function. Hence they're required but built-in.

I recommend you to use the base classes in polymer/polymer-tests.ts, I added those here so they could be used along with the definition files.

Please, ask me if you have any question about this "support" file.

**Comment by nippur72** [comment]
I wrote a quick implementation of the new Polymer 0.9 that supports `@decorators` (similar to PolymerDart). You might want to check it and, if you like, merge it when Polymer will get stable to 1.0.

The repo is [PolymerTS](https://github.com/nippur72/PolymerTS)

**Comment by enlight** [comment]
I've also started on some [typing for Polymer 1.0](https://github.com/enlight/polymer-typings), I'm adding on to them as the need arises, still need to add some tests too. I like what @nippur72 did with decorators so I've created [some decorators](https://github.com/enlight/polymer-ts-decorators) that work with the type definitions I'm writing.

**Comment by nippur72** [comment]
Definitions for Polymer 1.0 have been added (#4770). 

Please note these are different from [PolymerTS](https://github.com/nippur72/PolymerTS), that is you don't have `@decorators` and all the rest. I have to figure how to make the two coexist.
