### ISSUE TITLE
Definition request: material-ui

### ISSUE THREAD

**Issue by AyaMorisawa** [borisyankov/DefinitelyTyped#5619]
https://github.com/callemall/material-ui

**Comment by nojaf** [comment]
Created first attempt in https://github.com/borisyankov/DefinitelyTyped/pull/5736

**Comment by bjfletcher** [comment]
@AyaMorisawa @nojaf This would be useful.

A little bit background to this request.

TypeScript has just released a beta version of 1.6 that contains JSX/ReactJS support.

Material-UI is a popular component library with ReactJS.

There will definitely be many people wanting to use ReactJS and Material-UI as 3rd party libraries in TypeScript-based web projects.

**Comment by ngbrown** [comment]
I have a pretty complete implementation.  I'll submit a pull request after I add tests.

**Comment by use-strict** [comment]
@ngbrown, who can close this?

**Comment by ngbrown** [comment]
@use-strict the original requestor can close it, in this case, @AyaMorisawa, or a project maintainer. I'm not one, and I wouldn't worry too much about it.

**Comment by AyaMorisawa** [comment]
A definition file has been merged. Thank you.
