### ISSUE TITLE
UI-router $state.go has more than one implementation

### ISSUE THREAD

**Issue by dpsthree** [borisyankov/DefinitelyTyped#5652]
$state.go and $state.transitionTo accept either a String or a state object (IState). The interface only specifies the String version.

**Comment by dpsthree** [comment]
I have a pull request here: https://github.com/borisyankov/DefinitelyTyped/commit/6612806e0a1be58b4cfe37775c0f48ec3809fcfd

**Comment by vvakame** [comment]
closed by #5653
