### ISSUE TITLE
JS-Diff definitions incomplete

### ISSUE THREAD

**Issue by jimthedev** [borisyankov/DefinitelyTyped#5671]
There are definitions for https://github.com/kpdecker/jsdiff but they are slightly out of date. 

JsDiff.diffJson
JsDiff.createTwoFilesPatch
etc... 
are missing from the definitions.

**Comment by vvakame** [comment]
@jimthedev please send a pull request. I'll review it.

**Comment by aroder** [comment]
Added pull request #5965
