### ISSUE TITLE
core-js compilation fails

### ISSUE THREAD

**Issue by laurentiustamate94** [borisyankov/DefinitelyTyped#5685]
[This commit](https://github.com/borisyankov/DefinitelyTyped/commit/990caac6dc7eea22bf5329ad9da4e4a97eb6a9da) deletes the [ArrayLike<T>](https://github.com/borisyankov/DefinitelyTyped/commit/990caac6dc7eea22bf5329ad9da4e4a97eb6a9da#diff-8ceaaf0aa8bd195dcdcfb3b9e3757b1fL74) interface which is crucial for other properties in the `PromiseConstructor ` interface.

Please fix this critical issue.

**Comment by TeamworkGuy2** [comment]
core.d.ts already has an identical definition: 
https://github.com/Microsoft/TypeScript/blob/af05e46b2877edfbc239ade1a46d05b387568bd8/src/lib/core.d.ts#L1186

**Comment by laurentiustamate94** [comment]
Ok, but the current Visual Studio Community 2015 throws an error on this. I have the latest Typescript beta1.5 and I don't have those changes. What the solution would be in this case?

**Comment by laurentiustamate94** [comment]
Ok, I updated to the [lastest typescript](https://github.com/Microsoft/TypeScript/releases)
