### ISSUE TITLE
Confusing names of interfaces for SlickGrid event args

### ISSUE THREAD

**Issue by Koloto** [borisyankov/DefinitelyTyped#5729]
# Problem
Currently `Slick` module declares class `EventData`, which is used to simulate a DOM/jQuery event object:
```ts
	export class EventData {
		constructor();
		public stopPropagation(): void;
		public isPropagationStopped(): boolean;
		public stopImmediatePropagation(): void;
		public isImmediatePropagationStopped(): boolean;
	}
```
Also there are a lot of interfaces with the names like `On<Name>EventData`, e.g.
```ts
	export interface OnClickEventData {
		row: number;
		cell: number;
	}
```
`EventData` and `On<Name>EventData` describe different things: DOM event and SlickGrid event. But they have similar names and it confuse a lot.

# Proposal
The SlickGrid event object is usually named `args` (see `Event.notify` for example). So it's logically to rename `On<Name>EventData` to `On<Name>EventArgs`.

I can create a PR, but it will be a breaking change. So I want to discuss it with other contributors first.
@jbaldwin, @ljl, @Diullei, @vvakame, @derekcicerone, @benjaminjackman, @Igorbek, @Bartvds, @gscshoyru, @slozier, @styfle, @payojbaral, @ryiwamoto, @catbusstop what do you think?

**Comment by vvakame** [comment]
I'm not user of slickgrid now. You should doing to want. :wink:

**Comment by styfle** [comment]
@Koloto It sounds like this is simply a refactor due to a naming convention. I'm okay with the change.
