### ISSUE TITLE
interface ArrayLike is missing from latest version of core-js.d.ts

### ISSUE THREAD

**Issue by gregoryagu** [borisyankov/DefinitelyTyped#5780]
Somehow, interface ArrayLike has gone missing from core-js.d.ts.

It was in earlier version, but after upgrading to the latest, I had to add it by hand from an old version.

To reproduce, open core-js.ts in Visual Studio 15, and it will show numerous errors from the missing interface.

**Comment by MarenkovIgor** [comment]
I have faced with this issue too.

**Comment by billccn** [comment]
IIRC, the definition has been added to `lib.d.ts` in TS1.6 so it would conflict.

Currently the best way is to reproduce the definition in your own code and when you upgrade, the compiler will remind you to remove it.

**Comment by gregoryagu** [comment]
OK, I understand now.
