### ISSUE TITLE
Request Options missing formData

### ISSUE THREAD

**Issue by Shiak1** [borisyankov/DefinitelyTyped#5787]
As you can see [here](https://github.com/request/request/tree/master/examples#multipart) request has an option of passing in a property formData which then gets converted internally to a FormData instance for multipart data, the definition however is missing which causes typestrict errors in 1.6.0-beta.

Thanks in advance.

**Comment by horiuchi** [comment]
@Shiak1 Please fix this issue and send pull request!
I will review it.

**Comment by Shiak1** [comment]
@horiuchi Patch passed tests, looks like it's good to go.
