### ISSUE TITLE
Missing declaration in jake.d.ts at ExecOptions

### ISSUE THREAD

**Issue by eyalsk** [borisyankov/DefinitelyTyped#5854]
I had to pass windowsVerbatimArguments for jake to parse the arguments correctly, I'm not 100% sure what it does so I left the comment below empty but nonetheless it's a valid option, you can check the source to validate it.

I didn't find any documentation about it, odd.

The current declaration of the ExecOptions interface is as follow.
```
interface ExecOptions{
	/**
	 * print to stdout, default false
	 */

	printStdout?:boolean;
	/**
	 * print to stderr, default false
	 */
	printStderr?:boolean;

	/**
	 * stop execution on error, default true
	 */
	breakOnError?:boolean;
}
```
Whereas it should be like this.
```
interface ExecOptions{
	/**
	 * print to stdout, default false
	 */

	printStdout?:boolean;
	/**
	 * print to stderr, default false
	 */
	printStderr?:boolean;

	/**
	 * stop execution on error, default true
	 */
	breakOnError?:boolean;
	
	/**
	 * 
	 */
	windowsVerbatimArguments?: boolean
}
```

**Comment by vvakame** [comment]
please send a pull request. I'll review it.
