### ISSUE TITLE
webrtc, filewriter, filesystem NuGet packages outdated

### ISSUE THREAD

**Issue by slikts** [borisyankov/DefinitelyTyped#5904]
Not sure if this is the right place to report this, but these packages have errors such as having `bool` instead of `boolean` and also don't support `--noImplicitAny`.

**Comment by vvakame** [comment]
@staxmanade ?

**Comment by staxmanade** [comment]
@slikts can you look at the version you have installed? The most recent package was published from this repository at this commit https://github.com/borisyankov/DefinitelyTyped/blob/7c228c09302f51d19b6b93fcfc5decaf8e8bbaa2

https://www.nuget.org/packages/webrtc.TypeScript.DefinitelyTyped/ is up to version `0.2.0` (this morning when I checked)

Hope this helps,

**Comment by slikts** [comment]
I should have mentioned that the webrtc, filewriter and filesystem packages were installed as dependencies of the chrome package, sorry. The versions were 0.0.1, and manually upgrading them fixed it. Why doesn't the NuGet website or the manager inside of VS list the dependency versions? Also, why are the dependencies for the chrome package different in tsd?

**Comment by staxmanade** [comment]
This seems like a bug in NuGet (as document on this page http://docs.nuget.org/Create/Versioning) `empty = latest version.`

**Comment by xt0rted** [comment]
If you're using vs2015 then you're probably seeing the same issue reported in #5446
