### ISSUE TITLE
AngularJS IFilterFunc too restrictive

### ISSUE THREAD

**Issue by rcollette** [borisyankov/DefinitelyTyped#5931]
IFilterFunc in angular.d.ts appears to require an array as the first parameter and it also specifies that the return type is the same as the input type.  However, it is possible for the first parameter to not be an array and the output type may be different than the input type.

See this plnkr for an example of a single number being used as input and the return type of the filter function being a string.

http://plnkr.co/edit/xwMZe5g9YuYNhW2obMjG?p=preview

**Comment by albv** [comment]
+1, now IFilterFunc interface is good for 'filter' filter only https://code.angularjs.org/1.4.2/docs/api/ng/filter/filter

**Comment by use-strict** [comment]
Already created fix in https://github.com/borisyankov/DefinitelyTyped/pull/5948

**Comment by use-strict** [comment]
Can someone close this? :)

**Comment by vvakame** [comment]
thanks!
