### ISSUE TITLE
React Typings: SVGAttributes has no Class or Id Fields

### ISSUE THREAD

**Issue by JKillian** [borisyankov/DefinitelyTyped#5978]
`SVGAttributes` extends `DOMAttributes` which does not contain the `className` or `id` fields. This means that the following is invalid TSX:

```typescript
let element = <svg><circle class="foo" cx="0" cy="0" r="10"/></svg>
```

These attributes are present on the `HTMLAttributes` interface which also extends `DOMAttributes`. They should probably be moved from `HTMLAttributes` to `DOMAttributes`.

**Comment by jbrantly** [comment]
See #5893 which fixes the className part of this.

Agreed though in general that these need to be cleaned up.

**Comment by JKillian** [comment]
Thanks @jbrantly, I'll close this issue since this is already in the works
