### ISSUE TITLE
[angular-mocks.d.ts] error TS2304: Cannot find name 'module'

### ISSUE THREAD

**Issue by tkrotoff** [borisyankov/DefinitelyTyped#6167]
The use of `module` inside a unit test for a AngularJS 1.x controller now displays a TS error:
```TypeScript
// File MyCtrl.spec.ts
describe('MyCtrl', () => {
  beforeEach(module('app')); // <== error TS2304: Cannot find name 'module'

  // ...
});
```

This can be fixed by writing:
```TypeScript
  beforeEach(angular.mock.module('app'));
```

However, the AngularJS documentation says to write `module`: https://docs.angularjs.org/guide/module#unit-testing

**Comment by vvakame** [comment]
`beforeEach(angular.module('app'));` ?

**Comment by tkrotoff** [comment]
This does not work: `angular.module` declares a module, here we want to load module :)

**Comment by vvakame** [comment]
I remembered. check #5440 and #2072 :wink:

**Comment by tkrotoff** [comment]
Ok, thx. So this is an invalid issue
