### ISSUE TITLE
Missing require-context for Webpack

### ISSUE THREAD

**Issue by Ridermansb** [borisyankov/DefinitelyTyped#6170]
Hi @tkqubo .. thanks for your contribution.

Just one feedback:

    ERROR tests.webpack.ts
    error TS2339: Property 'context' does not exist on type 'NodeRequire'.

    ERROR tests.webpack.ts
    error TS2339: Property 'keys' does not exist on type 'IContextDefinition'.

Missing [require-context][require-context] definition:

Example `tests.webpack.ts` file for test

    var context = require.context('./test', true, /.+\.spec\.js?$/);
    context.keys().forEach(context);

[require-context]: https://webpack.github.io/docs/context.html#require-context

**Comment by tkqubo** [comment]
I think those definitions were added yesterday by this pr https://github.com/borisyankov/DefinitelyTyped/pull/6086
In addition to `webpack.d.ts`, you need to refer `webpack-env.d.ts` and the lines below can compile


```ts
/// <reference path="./webpack.d.ts" />
/// <reference path="./webpack-env.d.ts" />

var context = require.context('./test', true, /.+\.spec\.js?$/);
context.keys().forEach(context);
```

**Comment by Ridermansb** [comment]
I have add in `tsconfig.json` file using.. 


    ...
    "filesGlob": [
        "./**/*.ts"
    ],


How do I get these files?
I installed the definition using:

    tsd update webpack -riso


And only `/// <reference path="webpack/webpack.d.ts" />` is available

**Comment by tkqubo** [comment]
You can fetch `webpack-env.d.ts` by 

```sh
tsd update webpack-env -riso
```

or...  should it be combined into single `webpack.d.ts` file?

**Comment by Ridermansb** [comment]
I think that can be combined into single file :)

**Comment by tkqubo** [comment]
My pleasure! :guitar:

**Comment by tkqubo** [comment]
@Ridermansb Hi, I recently merged webpack-env.* into webpack ,but reverted it again since they should be used in a different context.  
c.f. https://github.com/borisyankov/DefinitelyTyped/pull/6243#commitcomment-13792564 

So if you want to refer require.context, you need to get webpack-env.d.ts independently of webpack.d.ts.
Thank you

**Comment by AlexLeung** [comment]
How can I get webpack-env.d.ts installed into my project via the typings command?

**Comment by tkqubo** [comment]
Could you try this?

```bash
typings install dt~webpack-env --global
```

**Comment by AlexLeung** [comment]
It works! Thanks!

**Comment by umasgn** [comment]
error TS2307: Cannot find module 'uglify-js'.
![err](https://cloud.githubusercontent.com/assets/12139440/17600865/106e4cc4-6023-11e6-8bf0-3ced7fd10d72.png)

**Comment by AlexLeung** [comment]
Peer dependencies are not automatically installed by typings. You need to install those yourself. Run `typings install --save --global dt~uglify-js`

**Comment by jrgleason** [comment]
I just tried `npm install --save-dev @types/webpack @types/webpack-env` and I still get...

```
ERROR in /Users/.../code/webpack-test/node_modules/@types/webpack-env/index.d.ts
(183,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'RequireFunction'.

ERROR in /Users/.../code/webpack-test/node_modules/@types/webpack-env/index.d.ts
(232,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'module' must be of type 'NodeModule', but here has type 'Module'.

ERROR in ./test/test.bundle.ts
(5,35): error TS2339: Property 'context' does not exist on type 'NodeRequire'.
```

**Comment by zzczzc004** [comment]
@jrgleason , I also have the same problem, it show there are two variables(require, module) conflicted in Node.JS and webpack-env. I think we should change the variables' name or not put the variable to global. I think this problem is the same as [8018](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8018).
```
(73,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'RequireFunction', but here has type 'NodeRequire'.
(85,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'module' must be of type 'Module', but here has type 'NodeModule'.
```

**Comment by AnimaMundi** [comment]
@zzczzc004 It seems you are also loading types for node, webpack-env types should be loaded instead of node types, not in addition to them.

**Comment by sjpurol** [comment]
@zzczzc004, `@types/webpack` includes `@types/node` as a dependency, thus installing both `@types/webpack` and `@types/webpack-env` resulted in the errors you described. Try only installing `@types/webpack-env`. This resolved the issue for me. 👍

**Comment by aalenliang** [comment]
I'm using node require and webpack require, I've installed 
@types/node
@types/webpack
@types/webpack-env

however, using 'require.context' I still got
error TS2339: Property 'context' does not exist on type 'NodeRequire'.

Any ideas?

**Comment by blackendstudios** [comment]
@AlexLeung @tkqubo by installing the typings definitions solved the problem for me

typings install dt~webpack-env --global

**Comment by rnons** [comment]
Isn't [wepack-env](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack-env/index.d.ts#L1) for the version 1.13

>  `// Type definitions for webpack (module API) 1.13`

Shouldn't `RequireContext` be added to `types/webpack/index.d.ts` as well?

**Comment by dennisat** [comment]
`npm install --save-dev @types/webpack-env`

and in tsconfig.json add it in the `types` property
example:
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "declaration": true,
    "declarationDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": false,
    "module": "commonjs",
    "target": "es6",
    "allowJs": false,
    "types": [
      "node",
      "webpack-env"
    ]
  },
  "files": [
    "src/index.ts"
  ],
  "compileOnSave": false
}
```
