### ISSUE TITLE
Type definition mismatch due to recent change to angular-ui-router.d.ts which breaks ui-router-extras.d.ts

### ISSUE THREAD

**Issue by skalidindi** [borisyankov/DefinitelyTyped#6175]
Recent changes to angular-ui-router.d.ts changed the types of some properties on IState. For example,

       views?: {};                        

changed to                 

       views?: { [name:string]: IState };

This breaks the type definition of IStickyState in the file ui-router-extras.d.ts

The interface IStickyState which extends angular.ui.IState has the property

        views?: {};   
which should be updated to

        views?: { [name:string]: IState };

**Comment by vigie** [comment]
Fixed by https://github.com/borisyankov/DefinitelyTyped/pull/6169/commits

**Comment by vvakame** [comment]
thanks!
