### ISSUE TITLE
lodash: Problems in types definitions for implicit/explicit chain

### ISSUE THREAD

**Issue by itchyny** [borisyankov/DefinitelyTyped#6208]
Hi, I have a problem with lodash.d.ts.

I get a type error with the following example.
```javascript
var x: number = _([1,2,3]).max(); // type error: Type 'LoDashWrapper<number>' is not assignable to type 'number'.
var y: number = _.chain([1,2,3]).max().value(); // fine
```
We can confirm that the both lines work well in a JavaScript console.
```javascript
> _([1,2,3]).max()
3
> _.chain([1,2,3]).max()
LodashWrapper {__wrapped__: Array[3], __actions__: Array[1], __chain__: true}
> _.chain([1,2,3]).max().value()
3
```
With the implicit chaining `_(array)` and the `max` function, the result value is returned instantly. The same problem occurs for `min`. Also, the type definition of `last` function holds the opposite problem.
```javascript
var x: number = _([1,2,3]).last(); // fine
var y: number = _.chain([1,2,3]).last().value(); // type error: Property 'value' does not exist on type 'number'.
```
The both lines should be accepted. Could you please fix the type definitions?

**Comment by vvakame** [comment]
@chrootsu ?

**Comment by chrootsu** [comment]
The PR with the fix was created

**Comment by itchyny** [comment]
Thank you @chrootsu for changing the type definition for `_.max`. I intended to point out the problems of the difference between `_(array)` and `_.chain(array)`; the former creates an array wrapper with implicit chaining and the latter creates a wrapper with explicit chaining. However in most case and in my product as well, implicit chaining is widely used and I've never used `_.chain`. Distinguishing the both kinds of wrappers in lodash.d.ts will be a tough work while most people would not use explicit chaining so I keep this issue closed. Thanks anyway.

**Comment by chrootsu** [comment]
@itchyny, glad I could help. ^_^
Yep, I know about malfunction of _.chain and have a set of commits with the almost complete fix of the issue. I will try to test it and send a PR in the next few days or at the weekend. Thanks for your report.
