### ISSUE TITLE
Bluebird join<R>

### ISSUE THREAD

**Issue by brianlagerman** [borisyankov/DefinitelyTyped#6267]
I seem to have hit a wall with the Bluebird join (R) definition. JavaScript reference: [bluebird join](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisejoinpromisethenablevalue-promises-function-handler---promise)

```javascript
	/**
	 * Like `Promise.all()` but instead of having to pass an array, the array is generated from the passed variadic arguments.
	 */
	// variadic array with promises of value
	static join<R>(...values: Promise.Thenable<R>[]): Promise<R[]>;
	// variadic array with values
	static join<R>(...values: R[]): Promise<R[]>;
```

Since the return type of each function can be different, I get compiler errors that the return type of the second (or third, forth...) argument is not assignable to the return type of the first. This makes sense as there is a single (R) generic. I've tried everything I can think of to tweak the definition, but nothing wants to work.

```javascript
function getSomeStuff() : Promise<SomeStuff> {}
function getOtherStuff() : Promise<OtherStuff> {}

Promise.join(getSomeStuff(), getOtherStuff(), (someStuff, otherStuff) => {});
```
...gives me 1) type 'R' cannot be inferred from usage and 2) OtherStuff is not SomeStuff.

**Comment by use-strict** [comment]
The compiler needs to find a common type to be able to infer the type parameter. There isn't much you can do from the definition. Remember type inference is just a convenience feature. If the compiler can't infer the type, you still need to give the type parameter explicitly, like this:
```typescript
Promise.join<string|number|Whatever>(a/*: string*/, b/*: number*/, c/*: Whatever*/);
// -> Promise<string|number|Whatever>
```

I thought of tuple types here as well, but unfortunately that doesn't work because you have variable arguments and that has to be typed as an array.

**Comment by brianlagerman** [comment]
OK, that helps me with the join declaration (the union types with the pipe is new to me). I'm assuming that the Thenable is always an array, or is there an easier, prettier way to break out the result set?

```typescript
Promise.join<string|number|Whatever>(a/*: string*/, b/*: number*/, c/*: Whatever*/)
.then((joinData) => {
     // Ugly, but I can live with it...
     var a = joinData[0];
     var b = joinData[1]:
     var what = joinData[2];
});
```

**Comment by use-strict** [comment]
You can maybe make it a bit less ugly with destructing:
```typescript
.then(([a, b, what]: [string, number, whatever]) => {
```

**Comment by brianlagerman** [comment]
Perfect, thanks a ton for your help!
