### ISSUE TITLE
Bug on node.d.ts file

### ISSUE THREAD

**Issue by rambarbosa** [borisyankov/DefinitelyTyped#6304]
I believe that there is a minor bug on the latest release of node.d.ts file: Ln 122, `isBuffer(obj: any): obj is Buffer` should be `isBuffer(obj: any): boolean;`

**Comment by vvakame** [comment]
it is valid for newest tsc. what version's do you use?

**Comment by rambarbosa** [comment]
I was using an older version... I just tried it with tsc v1.6.2 this is compiling correctly indeed.
Thank you for the feedback!

**Comment by marcalj** [comment]
I'm using tsd v1.6.2 and cannot compile due to this syntax. It's correct? :/

**Comment by horiuchi** [comment]
That's a new syntax by tsc v1.6.2.
via: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#user-defined-type-guard-functions

**Comment by marcalj** [comment]
Anyone using ```grunt-typescript``` just update to v0.8. Now compiles without errors :)
Thanks!
