### ISSUE TITLE
(node-redis) Error in declaration file when noImplicitAny is enabled

### ISSUE THREAD

**Issue by Roam-Cooper** [borisyankov/DefinitelyTyped#6344]
(node-redis) Please add var types/return types where appropriate, for users who have noImplicitAny enabled. :)

**Comment by horiuchi** [comment]
I think `node_redis/node_redis.d.ts` is old version of `redis/redis.d.ts`.
Please use the new version of redis definition(`redis/redis.d.ts`).

But I don't know why the old version is exists...
