### ISSUE TITLE
TypeScript 1.6 and highcharts.d.ts interface HighchartsOptions problems

### ISSUE THREAD

**Issue by terryaney** [borisyankov/DefinitelyTyped#6362]
For any of the properties on HighchartOptions that are |'ed between a single object and an array (i.e. xAxis?: HighchartsAxisOptions | HighchartsAxisOptions[];), if I try to use options.xAxis.{anything}, I get a compile error of:

Property 'categories' does not exist on type 'HighchartsAxisOptions | HighchartsAxisOptions[]'.

I fixed it by commenting out the | HighchartsAxisOptions[].  I'm very new to TypeScript and *.d.ts so I'm not sure if my set up is wrong or what.  The code seemed to work when I was on previous version of TypeScript/*.d.ts.  I just updated tonight and it then was broke, so I then refreshed my *.d.ts file as well.

Interesting point...in the project file, it said TypeScriptToolVersion: 1.4, so I uninstalled 1.6 (but in doing that I saw I had previously seemed to install version 1.5).  Anyway, uninstalling and reverting back to a previous version of *.d.ts (version 2.3.3 which didn't have the | array versions) still didn't work because of other TypeScript problems which I'm not sure how come they didn't fix themselves since I rolled back code.  So I reinstalled 1.6 and tried to move ahead.

Again, not sure if this is TypeScript, Visual Studio or *.d.ts problem, but thought I would submit it.

Thanks in advance.

**Comment by baltie** [comment]
xAxis can be both a concrete Axis object or an array of Axis objects, hence the definition. You can cast it to the variant you need. For instance:
var axis = <HighchartsAxisOptions> chart.xAxis;

After you install TypeScript 1.6, Visual Studio (2015 at least) and open your solution, Visual Studio should come up with a message box telling you that it can update your project to use TypeScript 1.6. If it doesn't, you can edit that yourself in the project file. It should just say 1.6 instead of 1.4.

**Comment by terryaney** [comment]
Thanks for the answer.  So I changed from:

```javascript
if (options.xAxis == undefined) {
    options.xAxis = <HighchartsAxisOptions>{};
}
                        
options.xAxis.categories = chartData.AsLinq<HighChartsDataRow>().Select(d => this.RemoveRBLEncoding(d.category) || "").ToArray();
```
to

```javascript
var xAxis = <HighchartsAxisOptions>options.xAxis || <HighchartsAxisOptions>{};
xAxis.categories = chartData.AsLinq<HighChartsDataRow>().Select(d => this.RemoveRBLEncoding(d.category) || "").ToArray();
options.xAxis = xAxis;
```

And it seemed to work.  That look about right to you?

**Comment by baltie** [comment]
Yes, that should work. :)
