### ISSUE TITLE
Bootstrap.datepicker datepicker methods have wrong return type

### ISSUE THREAD

**Issue by yjukaku** [borisyankov/DefinitelyTyped#6454]
The bootstrap.datepicker `datepicker(methodName : string)` methods can return a number of different things, not just a JQuery object.

For example, from the bootstrap.datepicker docs (http://bootstrap-datepicker.readthedocs.org/en/stable/methods.html)

```
getDate
Arguments: None

Returns a localized date object representing the internal date object of the first datepicker in the selection. For multidate pickers, returns the latest date selected.
```

Obviously this is a Date object.

**Comment by vvakame** [comment]
please send a pull request. I'll review it.

**Comment by yjukaku** [comment]
@vvakame Please see #6473
