### ISSUE TITLE
Getting error related to lodash typings recent update.

### ISSUE THREAD

**Issue by piyushchauhan2011** [borisyankov/DefinitelyTyped#6462]
![screen shot 2015-10-27 at 2 54 51 pm](https://cloud.githubusercontent.com/assets/693487/10749630/be129502-7cc0-11e5-9754-6722c5e62666.png)

We are getting this issue related to lodash typings.
Typescript version in use is 1.6.

Any help would be appreciated ?

**Comment by albv** [comment]
I have the same issue. Typescript 1.5, lodash 2.4.1.

**Comment by piyushchauhan2011** [comment]
Nice builds perfectly. Please merge.

Screenshot...
![screen shot 2015-10-28 at 12 00 48 pm](https://cloud.githubusercontent.com/assets/693487/10777071/97891bb2-7d6b-11e5-8d8e-0a75d6941861.png)
