### ISSUE TITLE
jquery.d.ts lacks event.originalEvent.pointerType

### ISSUE THREAD

**Issue by cveld** [borisyankov/DefinitelyTyped#6482]
I am currently working on a mobile first application and I need to target Internet Explorer 11 (desktop and phone) and Microsoft Edge among others. These browsers expose the event type `pointerdown` and `MSPointerDown` with a special property `pointerType`.
Certainly we could add `pointerType` to jquery.d.ts - what would be the best approach to get TypeScript support and have rich intellisense that also advises on browser compatibility?

FYI; currently the plain JavaScript (jQuery?) support from Web Essentials already provides support for `pointerType`.

**Comment by vvakame** [comment]
@johnnyreilly ?

**Comment by johnnyreilly** [comment]
Hi @cveld,

I think this probably doesn't belong in jquery.d.ts but you should be able to extend the definition of jquery to cater for this in the same way that jQuery plugins do. You might want to take a look at a jQuery plugin in DT and see if you can use that approach to get what you need.

Hope that helps.
