### ISSUE TITLE
Support for google closure library

### ISSUE THREAD

**Issue by ufon** [borisyankov/DefinitelyTyped#733]
Google closure library has a well documented javascript API.

Would be nice to have a typescript declaration file for it.

Thanks!

**Comment by 3x0dv5** [comment]
Take a look at: https://github.com/fivetran/DefinitelyTyped/tree/master/closure-library

**Comment by ufon** [comment]
Thank you!

**Comment by AllisonLamm** [comment]
Is this going to be added to repo? It looks like it has tests and everything it needs!
@VaclavObornik @3x0dv5
